# frozen_string_literal: true

require_relative "test_helper"
require "digest"
require "open3"

# MVP-0028 decision D6 — a same-ticket REVISION at GENERATION time: when this ticket's `Spec PR`
# field already names an open pull request, the runner reads its previous package straight off
# its branch and hands it to the provider as revision context, BEFORE generating anything.
#
# Driven through the real `claim-once` CLI against a REAL git repository with a REAL bare remote
# and a scriptable fake `gh`, for the same reason the publication test is: the pull request
# validation this reuses ({ExistingPullRequest}) and the branch read this adds
# ({PreviousSpecificationPackage}) are both genuinely about git and GitHub, and a stubbed one
# proves neither the fetch nor the fail-closed refusal.
class SpecificationGenerationRevisionTest < Minitest::Test
  ISSUE = "SR-700"
  PACKAGE = "specs/SR-700-add-an-export-button"
  BRANCH = "specrelay/spec/SR-700-add-an-export-button"
  PR_URL = "https://github.com/SpecRelay/SpecRelay-Specs/pull/7"

  PREVIOUS_FILES = {
    "spec.md" => "# SR-700: Add an export button\n\nGenerated by SpecRelay, round 1.\n",
    "analysis/business.md" => "# Business analysis\n\nThe reporter retypes rows by hand.\n",
    "analysis/technical.md" => "# Technical analysis\n\nExportReport is the seam.\n",
    "analysis/input-evidence.md" => "# Input evidence\n\nNo supporting input beyond the ticket.\n",
    # MAPIAI-63 CR-001: the previous round's OPEN question, carried on the pull request's branch.
    # A revision's whole purpose is to answer it, so it belongs in the package a revision reads.
    "open-questions.md" => <<~MD
      # Open questions — SR-700

      ## OQ-001

      - Why it blocks: the export format is unspecified.
      - Decision required: export CSV only, or CSV and XLSX.
      - Consequence: the wrong choice ships an unusable export.
    MD
  }.freeze

  # The Platform input bundle EXACTLY as `Jira::SpecCreation::Markdown` renders it once the
  # ticket carries comments — generated from that renderer, not hand-written. Comment 4001 is
  # SpecRelay's own marked publication comment; 4002 is the human answer to OQ-001.
  BUNDLE_WITH_ANSWER = <<~MD
    # Specification-creation input bundle — SR-700

    ## Jira description

    ```text
    The reporter retypes rows by hand.
    ```

    ## Jira comments

    ### Comment 4001 — Ada Lovelace — SpecRelay-generated (operational output, not Product Owner input)

    - Created: 2026-07-19T10:00:00.000+0000
    - Updated: 2026-07-19T10:00:00.000+0000

    ```text
    <!-- specrelay:spec-pr -->
    SpecRelay published a draft specification for this ticket.
    ```

    ### Comment 4002 — Ada Lovelace

    - Created: 2026-07-19T11:00:00.000+0000
    - Updated: 2026-07-19T11:00:00.000+0000

    ```text
    Answering OQ-001: export CSV only, and keep the existing column order.
    ```
  MD

  def setup
    @source, @specs, @temp = SpecificationWorkspace.build
    @io = StringIO.new
  end

  def teardown
    @platform&.stop
    FileUtils.remove_entry(@temp) if @temp && File.directory?(@temp)
    FileUtils.remove_entry(@gh_dir) if @gh_dir && File.directory?(@gh_dir)
  end

  # ------------------------------------------------------------------ the happy path

  def test_the_previous_packages_own_files_reach_the_provider_as_revision_context
    build_previous_package_on_branch
    capture = File.join(@temp, "captured-packet.json")
    provider = SpecificationWorkspace.write_recording_provider(
      File.join(@temp, "provider"), capture_to: capture, files: valid_generated_files
    )
    start_with_revision(provider: provider)

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    packet = JSON.parse(File.read(capture))
    previous = packet["revision"]["previous_files"]
    # `git show` returns trimmed content (`GitCommands#git_value`), so trailing whitespace is not
    # preserved byte-for-byte — irrelevant to revision context, which only needs the real text.
    PREVIOUS_FILES.each do |path, body|
      assert_equal body.strip, previous[path].to_s.strip, "expected #{path} to carry forward"
    end
  end

  # MAPIAI-63 CR-001 P2 — the defect's COMPLETE boundary, in one packet.
  #
  # MAPIAI-63 existed because each side looked correct in isolation: Platform captured the
  # comments, the runner faithfully carried whatever `content_markdown` it was given, and the
  # answer still never reached generation. Asserting the two halves separately would not have
  # caught it. This pins them together at the seam a provider actually reads: the current Jira
  # answer (its id AND its body) and the previous `OQ-001` present in the same provider-visible
  # packet. Live shape: comment 95859 answering MAPIAI-56 OQ-001.
  #
  # No provider and no network: a recording fake stands in for the provider, `gh` is a scripted
  # fake, and the remote is a local bare repository.
  def test_the_current_answer_comment_and_the_previous_open_question_reach_one_revision_packet
    build_previous_package_on_branch
    capture = File.join(@temp, "captured-packet.json")
    provider = SpecificationWorkspace.write_recording_provider(
      File.join(@temp, "provider"), capture_to: capture, files: valid_generated_files
    )
    start_with_revision(provider: provider, bundle_markdown: BUNDLE_WITH_ANSWER)

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    packet = JSON.parse(File.read(capture))

    # The previous question, read off the pull request's own branch.
    assert_includes packet.dig("revision", "previous_files").fetch("open-questions.md"), "## OQ-001"

    # The current answer, by id and by body, in the provider-visible bundle.
    delivered = packet.dig("input_bundle", "content_markdown")
    assert_includes delivered, "Comment 4002"
    assert_includes delivered, "Answering OQ-001: export CSV only, and keep the existing column order."

    # SpecRelay's own comment travels too, but stays labelled as operational output so it cannot
    # be read as the human answer.
    assert_includes delivered, "Comment 4001"
    assert_includes delivered, "SpecRelay-generated (operational output, not Product Owner input)"
  end

  def test_a_first_specification_carries_no_revision_block_at_all
    # No branch, no gh fake needed: `existing_pull_request_url` is absent from the payload.
    capture = File.join(@temp, "captured-packet.json")
    provider = SpecificationWorkspace.write_recording_provider(
      File.join(@temp, "provider"), capture_to: capture, files: valid_generated_files
    )
    @platform = FakePlatform.new(claim_payload: spec_creation_payload_for(issue_key: ISSUE)).start
    @config = build_config(provider: provider)

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli(env_extra: { "PATH" => ENV["PATH"] }), @io.string

    packet = JSON.parse(File.read(capture))
    assert_nil packet["revision"]
  end

  # ------------------------------------------------------------------ fail-closed: the PR itself

  def test_a_closed_spec_pr_refuses_before_generating_anything
    build_previous_package_on_branch
    start_with_revision(gh_seed: [ { "url" => PR_URL, "state" => "CLOSED", "headRefName" => BRANCH,
                                    "headRefOid" => git(@specs, "rev-parse", "origin/#{BRANCH}").strip } ])

    refute_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    assert_includes @io.string, "specification_revision_pull_request_unusable"
    assert_empty Dir.glob(File.join(@specs, PACKAGE, "*"))
  end

  def test_a_spec_pr_against_the_wrong_base_refuses
    build_previous_package_on_branch
    start_with_revision(gh_seed: [ { "url" => PR_URL, "state" => "OPEN", "headRefName" => BRANCH,
                                    "baseRefName" => "not-main",
                                    "headRefOid" => git(@specs, "rev-parse", "origin/#{BRANCH}").strip } ])

    refute_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    assert_includes @io.string, "specification_revision_pull_request_unusable"
  end

  # ------------------------------------------------------------------ fail-closed: the branch content

  def test_a_pull_request_whose_branch_does_not_exist_on_the_remote_refuses_as_unreadable
    # The PR validates fine (open, right base) but names a branch nothing ever pushed.
    start_with_revision(branch_exists: false)

    refute_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    assert_includes @io.string, "specification_revision_unreadable"
    assert_empty Dir.glob(File.join(@specs, PACKAGE, "*"))
  end

  def test_a_branch_that_exists_but_never_carried_a_package_at_this_path_refuses_as_unreadable
    ensure_remote_checkout
    git(@specs, "push", "-q", "origin", "HEAD:refs/heads/#{BRANCH}")
    start_with_revision

    refute_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    assert_includes @io.string, "specification_revision_unreadable"
    assert_includes @io.string, "does not carry a previously"
  end

  private

  # A minimally VALID package — every required `##` section with enough body to pass
  # {SpecrelayRunner::Specification::DocumentSet}. Content is irrelevant to these tests; only the
  # PACKET the provider receives is under test here.
  def valid_generated_files
    sections = SpecrelayRunner::Specification::DocumentSet::REQUIRED_SECTIONS
    body = "Filler content for this section, long enough to pass the minimum length check.\n\n"
    {
      "spec.md" => "# #{ISSUE} — a specification\n\n" +
        sections.fetch("spec.md").map { |h| "## #{h}\n\n#{body}" }.join,
      "analysis/business.md" => "# Business analysis — #{ISSUE}\n\n" +
        sections.fetch("analysis/business.md").map { |h| "## #{h}\n\n#{body}" }.join,
      "analysis/technical.md" => "# Technical analysis — #{ISSUE}\n\n" +
        sections.fetch("analysis/technical.md").map { |h| "## #{h}\n\n#{body}" }.join,
      "analysis/input-evidence.md" => "# Input evidence\n\nNo supporting input beyond the ticket.\n"
    }
  end

  def ensure_remote_checkout
    return if @bare

    git_init(@specs)
    File.write(File.join(@specs, "README.md"), "# SpecRelay specifications\n")
    git(@specs, "add", "README.md")
    commit(@specs, "initial")
    @bare = FakeGithub.add_remote(@specs, name: "SpecRelay-Specs")
    git(@specs, "push", "-q", "origin", "HEAD:refs/heads/main")
  end

  # A real git repository with a real bare remote, and the PREVIOUS package already committed to
  # the ticket's branch — exactly what a first publication (MVP-0027/D2-D4) would have left there.
  def build_previous_package_on_branch
    ensure_remote_checkout

    git(@specs, "checkout", "-q", "-b", BRANCH)
    PREVIOUS_FILES.each do |name, body|
      path = File.join(@specs, PACKAGE, name)
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, body)
      git(@specs, "add", File.join(PACKAGE, name))
    end
    commit(@specs, "#{ISSUE}: SpecRelay generated specification package")
    git(@specs, "push", "-q", "origin", "#{BRANCH}:refs/heads/#{BRANCH}")
    git(@specs, "checkout", "-q", "main")
  end

  def start_with_revision(provider: nil, gh_seed: [], branch_exists: true, bundle_markdown: nil)
    ensure_remote_checkout
    head_sha = branch_exists ? git(@specs, "rev-parse", "origin/#{BRANCH}").strip : "0" * 40
    seed = gh_seed.empty? ? [ { "url" => PR_URL, "state" => "OPEN", "headRefName" => BRANCH,
                              "baseRefName" => "main", "headRefOid" => head_sha } ] : gh_seed
    @gh_dir, = FakeGithub.gh_bin(mode: "ok", pull_request_url: PR_URL, bare: @bare, seed: seed)
    @platform = FakePlatform.new(
      claim_payload: spec_creation_payload_for(issue_key: ISSUE, content: bundle_markdown,
                                               existing_pull_request_url: PR_URL)
    ).start
    @config = build_config(provider: provider)
  end

  def build_config(provider: nil)
    path = File.join(Dir.mktmpdir("cfg"), "runner.yml")
    File.write(path, <<~YAML)
      platform:
        base_url: #{@platform.base_url}
        token_env: TEST_TOKEN
      runner:
        id: test-runner
        display_name: Test Runner
        claim_policy:
          mode: all_eligible
        specification:
          provider:
            kind: #{provider ? "command" : "fake"}
            command: #{provider}
          repository_roots:
            "SpecRelay/SpecRelay-Specs": #{@specs}
          context_plus:
            available: true
      workspace_roots:
        tiny-demo-workspace: #{@source}
    YAML
    SpecrelayRunner::Config.load(path)
  end

  def run_cli(env_extra: {})
    env = { "TEST_TOKEN" => FakePlatform::EXPECTED_TOKEN,
            "PATH" => "#{@gh_dir}:#{ENV['PATH']}", "HOME" => @temp }.merge(env_extra)
    SpecrelayRunner::CLI.run(%W[claim-once --config #{@config.source_path}], out: @io, err: @io, env: env)
  end

  def git_init(root)
    system("git", "init", "-q", root, exception: true)
    git(root, "config", "user.email", "test@specrelay.local")
    git(root, "config", "user.name", "SpecRelay Test")
    git(root, "symbolic-ref", "HEAD", "refs/heads/main")
  end

  def commit(root, message)
    git(root, "commit", "-q", "-m", message)
  end

  def git(root, *args)
    stdout, status = Open3.capture2("git", "-C", root, *args)
    raise "git #{args.join(' ')} failed: #{stdout}" unless status.success?

    stdout
  end
end
