# frozen_string_literal: true

require_relative "test_helper"
require "digest"
require "open3"

# Continuing a ticket whose specification was already PUBLISHED and ACCEPTED, in a task
# environment built after that round ended.
#
# The chain is the point, and no other suite walks it: an accepted publication commits the
# package with plumbing and pushes it, so it leaves the package on `origin/<branch>` and no local
# branch at all, and the environment is then released. Every other revision test starts from a
# hand-built snapshot and therefore never sees what the NEXT round inherits — an environment
# branched from the base, in which the published specification is not present.
#
# Driven through the real `claim-once` CLI twice, over a REAL task environment built by the
# project's own command, a REAL bare remote and a scriptable fake `gh`: each claim here is about
# what is on disk and in git after the previous phase, and a stubbed lifecycle proves neither.
class SpecificationPublishedContinuationTest < Minitest::Test
  ISSUE = "EXAMPLE-1"
  TASK = "EXAMPLE-1"
  PACKAGE = "specs/EXAMPLE-1-add-an-export-button"
  SPECS_SLUG = "SpecRelay/SpecRelay-Specs"
  PR_URL = "https://github.com/SpecRelay/SpecRelay-Specs/pull/7"

  # Somebody else's open work, on the same remote. The continuation imports the ticket's own
  # branch, so this branch's content must not arrive with it.
  UNRELATED_BRANCH = "somebody-elses-open-work"
  UNRELATED_FILE = "somebody-elses-file.md"

  PACKAGE_CONTENTS = {
    "spec.md" => "# EXAMPLE-1: Add an export button\n\nGenerated by SpecRelay, round 1.\n",
    "analysis/business.md" => "# Business analysis\n\nThe reporter retypes rows by hand.\n",
    "analysis/technical.md" => "# Technical analysis\n\nExportReport is the seam.\n",
    "analysis/input-evidence.md" => "# Input evidence\n\nNo supporting input beyond the ticket.\n"
  }.freeze

  def setup
    @built = SpecificationWorkspace.build_task_environment
    @root = @built.root
    @probe = File.join(@built.temp, "provider-probe.json")
    @io = StringIO.new
    install_two_round_project_command
  end

  def teardown
    @platform&.stop
    FileUtils.remove_entry(@built.temp) if @built && File.directory?(@built.temp)
  end

  # THE chain, end to end: an accepted publication, the release that follows it, a task
  # environment built afterwards, the SAME pull request continued in it, and the release of that
  # second round.
  #
  # The accepted round leaves only `origin/EXAMPLE-1`; the round after it starts from that
  # published head, so the package it revises is tracked history in the ticket's own branch rather
  # than a copy of the same bytes lying untracked beside it. And because it is tracked, the second
  # round's cleanup has to leave the environment releasable — which is what the closing phase
  # proves, through a project command that refuses a dirty worktree and an unmerged branch.
  #
  # Every mid-chain fact is read from the environment as the PROVIDER saw it — that is the moment
  # the revision context has to be real, and it is before this round writes a package of its own.
  def test_a_round_after_an_accepted_publication_continues_from_the_published_branch
    published = publish_the_accepted_package
    plant_unrelated_branch

    # The owned release RETAINS the local ref. That is the project's contract, not an oversight:
    # an automatic release discards the environment, never a branch that may hold work of its own.
    #
    # The retained ref is STALE. The package was committed and pushed from the runner's own
    # publication snapshot, so the environment's branch never moved, and the local ref is left at
    # the base the environment was created from. That is a known condition of this slice — the
    # next round below therefore has to reach the published head over the remote rather than
    # trusting what the checkout already has, which is exactly what it proves.
    assert local_branch?(TASK), "the owned release retains the local ref"
    refute_equal published, local_head(TASK), "the retained base is stale until it is aligned"
    assert_equal published, remote_head(TASK)

    assert_equal SpecrelayRunner::CLI::SUCCESS, continue_from_the_pull_request, @io.string

    assert_equal TASK, probe["branch"]
    assert_equal published, probe["head"], "the environment must start from the published head"
    assert_equal PACKAGE_CONTENTS.keys.sort, probe["tracked_package_files"].sort
    assert_empty untracked_package_paths, "the published package must not be reproduced untracked"

    # Only this ticket's branch was imported.
    refute probe["unrelated_file_present"], "unrelated branch content must stay out"
    assert_includes remote_branches, UNRELATED_BRANCH

    # The second round publishes onto the same branch and hands the environment back.
    revised = publish_the_continued_package
    refute_equal published, revised
    assert_equal revised, remote_head(TASK)
    refute_path_exists task_workspace, "the continued round must release the environment too"
    assert local_branch?(TASK), "the second owned release retains the local ref too"
    assert_equal 2, worktree_invocations.count("release #{TASK} --run-id #{SPEC_RUN} --json")

    # The SAME pull request, and only it. Each phase runs its own `gh` over the shared
    # pull-request state, so "opened nothing new" is counted from the invocations the continuation
    # really made rather than inferred from the url it reported back.
    assert_equal PR_URL, @platform.last_specification_publication["pull_request_url"]
    assert_equal 1, FakeGithub.pr_creates(@first_round_gh_log), "the first round opens exactly one"
    assert_equal 0, FakeGithub.pr_creates(@generation_gh_log), "generation opens none"
    assert_equal 0, FakeGithub.pr_creates(@second_round_gh_log),
                 "the continuation must commit onto the existing pull request, not open a second"
  end


  # ---------------------------------------------------------------- refusals on the same chain

  # An environment carrying a commit of its own beside the published head is RECONCILED only when
  # one head contains the other. Divergence is refused rather than merged: this reconstructs a
  # base, it does not resolve one.
  def test_a_reused_environment_diverged_from_the_published_head_refuses
    published = publish_the_accepted_package
    create_task_environment
    commit_beside_the_published_head

    assert_equal SpecrelayRunner::CLI::RUN_FAILED, continue_from_the_pull_request, @io.string
    assert_refused("has diverged from the published specification head #{published[0, 12]}")
  end

  # The published head is present but cannot be checked out. A `reset --hard` that fails leaves
  # the environment on some other commit, so the run must stop rather than hand a provider a tree
  # that is not the specification it was asked to revise.
  #
  # The index is locked, which is the state a crashed or concurrent git leaves behind, and is the
  # one condition that stops `reset` without touching the repository's content.
  def test_an_environment_the_published_head_cannot_be_checked_out_into_refuses
    published = publish_the_accepted_package
    create_task_environment
    lock_the_task_environment_index

    assert_equal SpecrelayRunner::CLI::RUN_FAILED, continue_from_the_pull_request, @io.string
    assert_refused("could not be put on #{TASK} at the published specification head " \
                   "#{published[0, 12]}")
  end

  # The environment's own checkout cannot reach the commit the pull request was read at.
  #
  # `repository_roots` and `workspace_roots` are separate settings, so the specification checkout
  # and the checkout the task environment is built from need not be the same clone. When they are
  # not, the published head has to be fetched into the environment — and when that fetch cannot
  # deliver it, "diverged" would be a lie about a commit this checkout has simply never seen.
  def test_a_published_head_the_environments_checkout_cannot_fetch_refuses
    detached = build_detached_workspace_checkout
    published = publish_the_accepted_package

    assert_equal SpecrelayRunner::CLI::RUN_FAILED,
                 continue_from_the_pull_request(workspace_root: detached), @io.string
    assert_refused("was read at #{published[0, 12]}, and this ticket's task environment cannot " \
                   "reach that commit")
  end

  private

  # Every refusal above must satisfy the same three things: the reason reaches Platform, no
  # provider ran, and the environment and its contents are still there.
  def assert_refused(reason)
    generation = @platform.last_specification_generation.to_h
    assert_includes generation["message"].to_s, reason
    refute_path_exists @probe, "no provider may run once the revision base could not be built"
    assert_path_exists task_workspace, "a refusal must leave the task environment alone"
    assert_path_exists File.join(task_workspace, "README.md")
  end

  # ---------------------------------------------------------------- phase 1: accepted round

  # An accepted publication, run the way the product runs it: the package is in the ticket's task
  # environment and in the retained publication snapshot, the runner commits and pushes it, and
  # the accepted result then removes the package and releases the environment. Returns the
  # published head.
  def publish_the_accepted_package
    create_task_environment
    write_package(task_package_root)
    build_isolated_workspace

    @gh_dir, @first_round_gh_log, @gh_state = FakeGithub.gh_bin(mode: "ok", pull_request_url: PR_URL,
                                                                bare: @built.bares["."])
    start_platform(spec_publication_payload_for(issue_key: ISSUE, files: @package_files,
                                                package_path: PACKAGE, branch: TASK,
                                                workspace_id: @workspace.id))

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    publication = @platform.last_specification_publication
    assert_equal "published", publication["outcome"], @io.string
    refute_path_exists task_workspace, "the accepted round must release the environment"

    publication["head_commit"]
  end

  # ---------------------------------------------------------------- phase 2: the next round

  # The same ticket, the same pull request, a task environment that does not exist yet.
  def continue_from_the_pull_request(workspace_root: nil)
    @workspace_root = workspace_root
    @platform.stop
    @io = StringIO.new
    @provider = write_probe_provider
    # A fresh invocation log and the SAME pull-request state: this round must find the pull
    # request the accepted round really created.
    @gh_dir, @generation_gh_log = FakeGithub.gh_bin(mode: "ok", pull_request_url: PR_URL,
                                                    bare: @built.bares["."], state: @gh_state)
    start_platform(spec_creation_payload_for(issue_key: ISSUE, existing_pull_request_url: PR_URL),
                   workspace_root: workspace_root)
    run_cli
  end

  # The provider under test: a real process that records the ENVIRONMENT it was handed, in git's
  # own terms, before it answers. "The package is tracked at the published head" is a fact about
  # the tree a provider revises, so it is read from that tree at that moment rather than from the
  # runner's log or from the state this round goes on to write.
  def write_probe_provider
    dir = Dir.mktmpdir("claude-stub", @built.temp)
    package = PACKAGE
    SpecificationWorkspace.write_executable(File.join(dir, "claude"), <<~RUBY)
      #!/usr/bin/env ruby
      require "json"
      if ARGV.first == "--version"
        puts "1.0.0"
        exit 0
      end
      exit 0 if %w[auth login].include?(ARGV.first)

      def git(*args) = IO.popen([ "git", *args ], err: :close, &:read).to_s

      File.write(#{@probe.inspect}, JSON.generate(
        "head" => git("rev-parse", "HEAD").strip,
        "branch" => git("symbolic-ref", "--quiet", "--short", "HEAD").strip,
        "tracked_package_files" => git("ls-files", "--", #{package.inspect})
                                     .split("\\n").map { |path| path.delete_prefix(#{"#{package}/".inspect}) },
        "status" => git("status", "--porcelain", "--untracked-files=all").split("\\n"),
        "unrelated_file_present" => File.exist?(#{UNRELATED_FILE.inspect})
      ))

      puts JSON.generate("type" => "system", "subtype" => "init")
      puts JSON.generate("type" => "result", "subtype" => "success", "is_error" => false,
                         "result" => JSON.generate(#{SpecificationWorkspace.valid_documents(ISSUE).to_json}))
    RUBY
    dir
  end

  # ---------------------------------------------------------------- phase 3: publishing round two

  # The package the continuation round actually generated, published onto the SAME pull request
  # and accepted — so the cleanup and the release run over a task environment whose package is the
  # branch's own tracked history. Returns the new published head.
  #
  # Everything the publication claim carries is read back from what the generation round REPORTED,
  # because that is what Platform would hand a runner here; a hand-built package would describe a
  # round this chain did not run.
  def publish_the_continued_package
    generated = @platform.last_specification_generation.fetch("package")
    workspace_id = @platform.last_specification_generation.dig("package_workspace", "id")
    @platform.stop
    @io = StringIO.new
    @provider = nil
    @gh_dir, @second_round_gh_log = FakeGithub.gh_bin(mode: "ok", pull_request_url: PR_URL,
                                                      bare: @built.bares["."], state: @gh_state)
    start_platform(spec_publication_payload_for(
                     issue_key: ISSUE, files: generated.fetch("files"),
                     package_path: generated.fetch("path"), branch: TASK,
                     workspace_id: workspace_id, existing_pull_request_url: PR_URL
                   ))

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    publication = @platform.last_specification_publication
    assert_equal "published", publication["outcome"], @io.string
    publication["head_commit"]
  end

  # ---------------------------------------------------------------- observation

  def probe = @probe_read ||= JSON.parse(File.read(@probe))

  def untracked_package_paths
    probe["status"].select { |line| line.start_with?("??") && line.include?(PACKAGE) }
  end

  # The environment the run under way is building, which is not always the one the accepted round
  # used: a refusal test may point the run at a different checkout of the same repository.
  def task_workspace = File.join(@workspace_root || @root, ".runs", "worktrees", TASK)
  def task_package_root = File.join(task_workspace, PACKAGE)

  def worktree_invocations
    File.exist?(@built.worktree_log) ? File.read(@built.worktree_log).lines.map(&:strip) : []
  end

  def local_branch?(branch)
    _out, status = SpecificationWorkspace.git(@root, "rev-parse", "--verify", "--quiet",
                                              "refs/heads/#{branch}")
    status.success?
  end

  # The commit the RETAINED local ref points at. An owned release takes the environment down and
  # leaves the branch, so this is what a later round finds already in the checkout.
  def local_head(branch)
    SpecificationWorkspace.git!(@root, "rev-parse", "refs/heads/#{branch}").strip
  end

  def remote_head(branch)
    SpecificationWorkspace.git!(@built.bares["."], "rev-parse", "refs/heads/#{branch}").strip
  end

  def remote_branches
    SpecificationWorkspace.git!(@built.bares["."], "for-each-ref", "--format=%(refname:short)",
                                "refs/heads").split("\n")
  end

  # ---------------------------------------------------------------- harness

  # A project command that can build the SAME ticket's environment twice, and that refuses to
  # release one it is not safe to release.
  #
  # The shared fixture command always creates with `-b` and releases only the workspace worktree,
  # so a second `create` fails on the branch and the components the first one left behind. The
  # real engine reuses an existing canonical branch and releases every worktree it made, which is
  # the only reason a ticket can be worked on again after a round — and this chain is about what
  # the second round inherits, so the command has to behave like the engine it stands in for.
  #
  # Two of those behaviours are load-bearing HERE and are therefore git's own, not a fixture's
  # imitation of the engine's release blockers:
  #
  #   * `worktree remove` WITHOUT `--force` refuses a worktree holding modified or untracked
  #     files, which is the engine's "uncommitted task artifacts" blocker;
  #   * `branch -d` refuses a branch whose commits are not contained in its upstream or in HEAD,
  #     which is the engine's "ahead of its upstream" blocker.
  #
  # `--set-upstream-to` mirrors the engine for the same reason: a ticket whose branch is already
  # published gets the tracking relationship, without which a branch put on that published head
  # reads as unpushed local work.
  def install_two_round_project_command
    components = SpecificationWorkspace::TASK_COMPONENTS.join(" ")
    SpecificationWorkspace.write_executable(File.join(@root, "bin", "worktree"), <<~SH)
      #!/usr/bin/env sh
      set -eu
      ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
      mkdir -p "$ROOT_DIR/.runs"
      echo "$*" >> "$ROOT_DIR/.runs/worktree.log"
      #{ProjectCommand.arguments}
      WT="$ROOT_DIR/.runs/worktrees/$TASK"
      attach() {
        if git -C "$1" show-ref --verify --quiet "refs/heads/$3"; then
          git -C "$1" worktree add -q "$2" "$3"
        else
          git -C "$1" worktree add -q -b "$3" "$2" HEAD
        fi
        if git -C "$1" show-ref --verify --quiet "refs/remotes/origin/$3"; then
          git -C "$1" branch -q --set-upstream-to "origin/$3" "$3"
        fi
      }
      case "$VERB" in
        create)
          mkdir -p "$ROOT_DIR/.runs/worktrees"
          attach "$ROOT_DIR" "$WT" "$TASK"
          for repo in #{components}; do attach "$ROOT_DIR/$repo" "$WT/$repo" "$TASK"; done
          #{ProjectCommand.record_owner}
          ;;
        status)
          #{ProjectCommand.status_case}
          ;;
        release)
          #{ProjectCommand.release_guard}
          for repo in #{components}; do
            git -C "$ROOT_DIR/$repo" worktree remove --force "$WT/$repo" || true
          done
          if [ -n "$RUN_ID" ]; then
            git -C "$ROOT_DIR" worktree remove --force "$WT"
          else
            for repo in #{components}; do git -C "$ROOT_DIR/$repo" branch -D "$TASK" || true; done
            git -C "$ROOT_DIR" worktree remove "$WT"
            git -C "$ROOT_DIR" branch -d "$TASK"
          fi
          #{ProjectCommand.release_report}
          ;;
        *) echo "usage: worktree create|status|release <task>" >&2; exit 1 ;;
      esac
    SH
  end

  # ---------------------------------------------------------------- the refused states

  # A commit of the environment's own, on the canonical branch, that the published head does not
  # contain and which does not contain it.
  def commit_beside_the_published_head
    File.write(File.join(task_workspace, "beside.md"), "work this environment did on its own\n")
    SpecificationWorkspace.git!(task_workspace, "add", "-A")
    SpecificationWorkspace.git!(task_workspace, "-c", "user.email=someone@specrelay.local",
                                "-c", "user.name=Someone Else", "commit", "-q",
                                "-m", "work beside the published head")
  end

  # What a crashed or concurrent git leaves behind. `reset` cannot write the index while it is
  # there, and nothing else this run does before the reset needs to.
  def lock_the_task_environment_index
    git_dir = SpecificationWorkspace.git!(task_workspace, "rev-parse", "--absolute-git-dir").strip
    File.write(File.join(git_dir, "index.lock"), "")
  end

  # A checkout of the ticket's repository that is NOT the one the specification is read from: same
  # GitHub identity, so it is still the specification repository as far as the run is concerned,
  # but served by a remote that never received the publication. Built BEFORE the accepted round
  # pushes, so the published commit is in neither its object database nor its remote.
  def build_detached_workspace_checkout
    root = File.join(@built.temp, "workspace-checkout")
    stale = File.join(@built.temp, "stale-origin.git")
    SpecificationWorkspace.git!(@built.temp, "clone", "--quiet", @built.bares["."], root)
    SpecificationWorkspace.git!(@built.temp, "clone", "--quiet", "--bare", root, stale)
    FakeGithub.add_remote(root, name: SpecificationWorkspace::SPECS_REPOSITORY)
    FakeGithub.serve_locally(root, stale)
    install_workspace_only_project_command(root)
    root
  end

  # The project command for that checkout. It owns no component repositories, so it builds the
  # workspace worktree and nothing else — a project defines its own task environment, and this one
  # is a single repository.
  def install_workspace_only_project_command(root)
    SpecificationWorkspace.write_executable(File.join(root, "bin", "worktree"), <<~SH)
      #!/usr/bin/env sh
      set -eu
      ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
      mkdir -p "$ROOT_DIR/.runs"
      #{ProjectCommand.arguments}
      WT="$ROOT_DIR/.runs/worktrees/$TASK"
      case "$VERB" in
        create)
          mkdir -p "$ROOT_DIR/.runs/worktrees"
          if git -C "$ROOT_DIR" show-ref --verify --quiet "refs/heads/$TASK"; then
            git -C "$ROOT_DIR" worktree add -q "$WT" "$TASK"
          else
            git -C "$ROOT_DIR" worktree add -q -b "$TASK" "$WT" HEAD
          fi
          #{ProjectCommand.record_owner}
          ;;
        status)
          #{ProjectCommand.status_case}
          ;;
        release)
          #{ProjectCommand.release_guard}
          if [ -n "$RUN_ID" ]; then
            git -C "$ROOT_DIR" worktree remove --force "$WT"
          else
            git -C "$ROOT_DIR" worktree remove "$WT"
            git -C "$ROOT_DIR" branch -d "$TASK"
          fi
          #{ProjectCommand.release_report}
          ;;
        *) echo "usage: worktree create|status|release <task>" >&2; exit 1 ;;
      esac
    SH
  end

  def create_task_environment
    out, status = Open3.capture2e(File.join(@root, "bin", "worktree"), "create", TASK,
                                  "--run-id", SPEC_RUN, chdir: @root)
    raise "bin/worktree create failed: #{out}" unless status.success?
  end

  # An open branch of somebody else's, pushed to the SAME remote. Made in its own clone so the
  # ticket's repositories are left exactly as the accepted round left them.
  def plant_unrelated_branch
    clone = File.join(@built.temp, "somebody-elses-clone")
    out, status = Open3.capture2e("git", "clone", "--quiet", @built.bares["."], clone)
    raise "git clone failed: #{out}" unless status.success?

    SpecificationWorkspace.git!(clone, "checkout", "-q", "-b", UNRELATED_BRANCH)
    File.write(File.join(clone, UNRELATED_FILE), "half-finished work of my own\n")
    SpecificationWorkspace.git!(clone, "add", "-A")
    SpecificationWorkspace.git!(clone, "-c", "user.email=someone@specrelay.local",
                                "-c", "user.name=Someone Else", "commit", "-q", "-m", "my own work")
    SpecificationWorkspace.git!(clone, "push", "-q", "origin", UNRELATED_BRANCH)
  end

  def write_package(root)
    @package_files = PACKAGE_CONTENTS.map do |name, body|
      path = File.join(root, name)
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, body)
      { "path" => name, "sha256" => Digest::SHA256.hexdigest(body), "bytes" => body.bytesize }
    end
  end

  WrittenFile = SpecrelayRunner::Specification::PackageWriter::WrittenFile

  # The retained publication snapshot, holding the SAME bytes as the task environment, built
  # through the production store so publication resumes the shape generation produces.
  def build_isolated_workspace
    store = SpecrelayRunner::Specification::PackageWorkspaceStore.new(
      root: SpecificationWorkspace.package_workspace_root(@built.temp), env: { "PATH" => ENV["PATH"] }
    )
    store.prepare!
    commands = SpecrelayRunner::Specification::GitCommands.new(checkout_root: @root,
                                                               env: { "PATH" => ENV["PATH"] })
    @workspace = store.create(
      commands: commands, clock: Time,
      base_commit: SpecificationWorkspace.git!(@root, "rev-parse", "HEAD").strip,
      identity: { "run_id" => "run_spec123", "runner_execution_id" => "rex_spec123",
                  "runner_id" => "test-runner", "runner_public_id" => "",
                  "repository_slug" => SPECS_SLUG,
                  "repository_url" => "https://github.com/SpecRelay/SpecRelay-Specs",
                  "package_path" => PACKAGE }
    )
    write_package(File.join(@workspace.worktree_root, PACKAGE))
    @workspace.finalize!(files: @package_files.map do |file|
      WrittenFile.new(path: file["path"], sha256: file["sha256"], bytes: file["bytes"])
    end)
  end

  def start_platform(payload, workspace_root: nil)
    @platform = FakePlatform.new(claim_payload: payload).start
    @config = build_config(workspace_root: workspace_root)
  end

  def build_config(workspace_root: nil)
    path = File.join(Dir.mktmpdir("cfg", @built.temp), "runner.yml")
    File.write(path, <<~YAML)
      platform:
        base_url: #{@platform.base_url}
        token_env: TEST_TOKEN
      runner:
        id: test-runner
        display_name: Test Runner
        claim_policy:
          mode: all_eligible
        specification:
          repository_roots:
            "#{SPECS_SLUG}": #{@root}
          context_plus:
            available: true
      workspace_roots:
        tiny-demo-workspace: #{workspace_root || @root}
    YAML
    SpecrelayRunner::Config.load(path)
  end

  def run_cli
    path = [ @provider, @gh_dir, ENV["PATH"] ].compact.join(File::PATH_SEPARATOR)
    env = { "TEST_TOKEN" => FakePlatform::EXPECTED_TOKEN, "PATH" => path }
          .merge(SpecificationWorkspace.lane_env(@built.temp))
    SpecrelayRunner::CLI.run(%W[claim-once --config #{@config.source_path}], out: @io, err: @io, env: env)
  end
end
