# frozen_string_literal: true

require_relative "test_helper"
require "digest"
require "open3"

# Returning the ticket's task environment once a specification publication has been ACCEPTED.
#
# Generation deliberately leaves its package in that environment, beside the code it describes,
# and until now nothing took the environment back: a ticket whose specification was published
# still held a worktree, and the preview lane addresses the same task id.
#
# Driven through the real `claim-once` CLI against the real fake Platform, over a REAL task
# environment built by the project's OWN `bin/worktree` — because every claim here is about what
# is left on disk and which project command was invoked, and a stubbed lifecycle proves neither.
class SpecificationTaskEnvironmentReleaseTest < Minitest::Test
  ISSUE = "EXAMPLE-1"
  TASK = "EXAMPLE-1"
  PACKAGE = "specs/EXAMPLE-1-add-an-export-button"
  PR_URL = "https://github.com/SpecRelay/SpecRelay-Specs/pull/7"

  PACKAGE_CONTENTS = {
    "spec.md" => "# EXAMPLE-1: Add an export button\n\nGenerated by SpecRelay.\n",
    "analysis/business.md" => "# Business analysis\n\nThe reporter retypes rows by hand.\n",
    "analysis/technical.md" => "# Technical analysis\n\nExportReport is the seam.\n",
    "generation-manifest.json" => "{\n  \"generated_by\": \"specrelay\"\n}\n"
  }.freeze

  def setup
    @built = SpecificationWorkspace.build_task_environment
    @root = @built.root
    @io = StringIO.new
    create_task_environment
    write_package(task_package_root)
    build_isolated_workspace
  end

  def teardown
    @platform&.stop
    FileUtils.remove_entry(@built.temp) if @built && File.directory?(@built.temp)
    FileUtils.remove_entry(@gh_dir) if @gh_dir && File.directory?(@gh_dir)
  end

  # ---------------------------------------------------------------- accepted cleanup

  # The outcome. Platform accepted the publication, so the local package is a duplicate of
  # committed history: it is removed from the task environment and the project's own release
  # command takes the environment down.
  def test_an_accepted_publication_removes_the_package_and_releases_the_environment
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    assert_equal "published", @platform.last_specification_publication["outcome"], @io.string

    assert_includes worktree_invocations, "release #{TASK}"
    refute File.exist?(task_workspace), "the released environment must be gone"
  end

  # Only the package. The environment's own repositories and their working trees are the project's
  # to take down, so the removal is scoped to the recorded package folder and the release command
  # does the rest — proved by removing the package and then declining to release.
  def test_only_the_recorded_package_folder_is_removed_before_the_release_is_invoked
    start_platform(release_mode: "refuse")

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    refute File.exist?(task_package_root), "the accepted package must be removed"
    assert_path_exists File.join(task_workspace, "README.md")
    assert_path_exists File.join(task_workspace, "component-a", "app", "services", "export_report.rb")
    assert_includes @io.string, "still allocated"
  end

  # ---------------------------------------------------------------- user-dirty protection

  # Somebody else's uncommitted work. The environment is not this run's to take down, and the
  # package is not removed either: deleting inside an environment a person is using, and then
  # releasing it, is the one failure this guard exists to prevent.
  def test_unrelated_uncommitted_work_blocks_both_the_removal_and_the_release
    dirty_a_component_repository
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    assert_equal "published", @platform.last_specification_publication["outcome"], @io.string

    assert_path_exists File.join(task_package_root, "spec.md")
    refute_includes worktree_invocations, "release #{TASK}"
    assert_path_exists task_workspace
    assert_includes @io.string, "was left in this ticket's task environment"
    assert_includes @io.string, "uncommitted"
  end

  # ---------------------------------------------------------------- modified generated bytes

  # The package on disk is no longer the one Platform accepted, so it is EVIDENCE of an edit
  # rather than a duplicate of committed history. The publication itself still succeeds — it
  # publishes the verified snapshot — and nothing is deleted or released.
  def test_a_generated_file_edited_in_the_task_environment_blocks_the_cleanup
    File.write(File.join(task_package_root, "spec.md"), "# edited by hand after generation\n")
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    assert_equal "published", @platform.last_specification_publication["outcome"], @io.string

    assert_equal "# edited by hand after generation\n", File.read(File.join(task_package_root, "spec.md"))
    refute_includes worktree_invocations, "release #{TASK}"
    assert_includes @io.string, SpecrelayRunner::Specification::PackageVerification::MISMATCH
  end

  # A file the accepted package does not describe, beside the ones it does. Digests alone never
  # see this: every recorded file matches and one more would be deleted with them.
  def test_an_unrecorded_file_beside_the_package_blocks_the_cleanup
    File.write(File.join(task_package_root, "notes-of-my-own.md"), "my working notes\n")
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    assert_path_exists File.join(task_package_root, "notes-of-my-own.md")
    assert_path_exists File.join(task_package_root, "spec.md")
    refute_includes worktree_invocations, "release #{TASK}"
    assert_includes @io.string, SpecrelayRunner::Specification::PackageVerification::ALTERED
  end

  # A package folder replaced by a symbolic link. Nothing outside the task environment may be
  # deleted, so the link is refused rather than followed.
  def test_a_symlinked_package_folder_is_refused_and_nothing_outside_is_deleted
    outside = File.join(@built.temp, "somebody-elses-package")
    FileUtils.mv(task_package_root, outside)
    File.symlink(outside, task_package_root)
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    assert_path_exists File.join(outside, "spec.md")
    refute_includes worktree_invocations, "release #{TASK}"
    assert_includes @io.string, SpecrelayRunner::Specification::PackageVerification::ALTERED
  end

  # ---------------------------------------------------------------- non-accepted retention

  # Platform REFUSED the result. It holds no record, so the package is the replay evidence a
  # retry publishes from and the environment stays where the operator left it.
  def test_a_refused_publication_retains_the_package_and_the_environment
    start_platform
    @platform.publication_response = [ 422, { error: "not acceptable right now" } ]

    assert_equal SpecrelayRunner::CLI::RUN_FAILED, run_cli, @io.string

    assert_path_exists File.join(task_package_root, "spec.md")
    refute_includes worktree_invocations, "release #{TASK}"
    assert_path_exists task_workspace
  end

  # The response was LOST. Platform holds no record either way, so the run is offered again and
  # the package has to survive for the replay to converge on the same commit.
  def test_an_unreachable_platform_retains_the_package_and_the_environment
    start_platform
    @platform.publication_response = [ 500, { error: "internal server error" } ]

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    assert_path_exists File.join(task_package_root, "spec.md")
    refute_includes worktree_invocations, "release #{TASK}"
  end

  # A failure BEFORE the publication reaches GitHub. Nothing was accepted, so nothing is cleaned.
  def test_a_failed_publication_retains_the_package_and_the_environment
    start_platform(gh_mode: "unauthenticated")

    assert_equal SpecrelayRunner::CLI::RUN_FAILED, run_cli, @io.string

    assert_path_exists File.join(task_package_root, "spec.md")
    refute_includes worktree_invocations, "release #{TASK}"
  end

  private

  def task_workspace = @built.task_workspace(TASK)
  def task_package_root = File.join(task_workspace, PACKAGE)

  def worktree_invocations
    File.exist?(@built.worktree_log) ? File.read(@built.worktree_log).split("\n") : []
  end

  # The environment the project's own command builds, exactly as generation would have left it.
  def create_task_environment
    out, status = Open3.capture2e(File.join(@root, "bin", "worktree"), "create", TASK, chdir: @root)
    raise "bin/worktree create failed: #{out}" unless status.success?
  end

  # An operator's own edit to a tracked file of a CONTAINED repository — the shape a per-repository
  # inspection catches and the workspace repository's own `git status` cannot see.
  def dirty_a_component_repository
    path = File.join(task_workspace, "component-a", "app", "services", "export_report.rb")
    File.write(path, "#{File.read(path)}# my own half-finished change\n")
  end

  def write_package(root)
    @package_files = PACKAGE_CONTENTS.map do |name, body|
      path = File.join(root, name)
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, body)
      { "path" => name, "sha256" => Digest::SHA256.hexdigest(body), "bytes" => body.bytesize }
    end
  end

  WrittenFile = SpecrelayRunner::Specification::PackageWriter::WrittenFile

  def store
    @store ||= SpecrelayRunner::Specification::PackageWorkspaceStore.new(
      root: SpecificationWorkspace.package_workspace_root(@built.temp), env: { "PATH" => ENV["PATH"] }
    )
  end

  # The retained publication snapshot, holding the SAME bytes as the task environment, built
  # through the production store so publication resumes the shape generation produces.
  def build_isolated_workspace
    store.prepare!
    commands = SpecrelayRunner::Specification::GitCommands.new(checkout_root: @root,
                                                               env: { "PATH" => ENV["PATH"] })
    @workspace = store.create(
      commands: commands, clock: Time, base_commit: git(@root, "rev-parse", "HEAD").strip,
      identity: {
        "run_id" => "run_spec123", "runner_execution_id" => "rex_spec123",
        "runner_id" => "test-runner", "runner_public_id" => "",
        "repository_slug" => "SpecRelay/SpecRelay-Specs",
        "repository_url" => "https://github.com/SpecRelay/SpecRelay-Specs",
        "package_path" => PACKAGE
      }
    )
    write_package(File.join(@workspace.worktree_root, PACKAGE))
    @workspace.finalize!(files: @package_files.map do |file|
      WrittenFile.new(path: file["path"], sha256: file["sha256"], bytes: file["bytes"])
    end)
  end

  def start_platform(gh_mode: "ok", release_mode: nil)
    refuse_release! if release_mode == "refuse"
    @gh_dir, @gh_log, = FakeGithub.gh_bin(mode: gh_mode, pull_request_url: PR_URL,
                                          bare: @built.bares["."])
    @platform = FakePlatform.new(claim_payload: publication_payload).start
    @config = build_config
  end

  # A project whose `release` fails, so "the package was removed and the environment was not" is
  # an observable state rather than an argument about ordering.
  def refuse_release!
    path = File.join(@root, "bin", "worktree")
    body = File.read(path).sub('release) git -C "$ROOT_DIR" worktree remove --force "$WT" ;;',
                               'release) echo "release is not available" >&2; exit 9 ;;')
    File.write(path, body)
    FileUtils.chmod(0o755, path)
  end

  def publication_payload
    spec_publication_payload_for(issue_key: ISSUE, files: @package_files, package_path: PACKAGE,
                                 branch: TASK, workspace_id: @workspace.id)
  end

  def build_config
    path = File.join(Dir.mktmpdir("cfg", @built.temp), "runner.yml")
    File.write(path, <<~YAML)
      platform:
        base_url: #{@platform.base_url}
        token_env: TEST_TOKEN
      runner:
        id: test-runner
        display_name: Test Runner
        claim_policy:
          mode: all_eligible
        specification:
          provider:
            kind: fake
          repository_roots:
            "SpecRelay/SpecRelay-Specs": #{@root}
          context_plus:
            available: true
      workspace_roots:
        tiny-demo-workspace: #{@root}
    YAML
    SpecrelayRunner::Config.load(path)
  end

  def run_cli
    env = { "TEST_TOKEN" => FakePlatform::EXPECTED_TOKEN,
            "PATH" => "#{@gh_dir}:#{ENV['PATH']}", "HOME" => @built.temp }
    SpecrelayRunner::CLI.run(%W[claim-once --config #{@config.source_path}], out: @io, err: @io, env: env)
  end

  def git(root, *args)
    out, status = Open3.capture2e("git", "-C", root, *args)
    raise "git #{args.join(' ')} failed: #{out}" unless status.success?

    out
  end
end
