# frozen_string_literal: true

require_relative "test_helper"
require "digest"
require "open3"

# Returning the ticket's task environment once a specification publication has been ACCEPTED.
#
# Generation deliberately leaves its package in that environment, beside the code it describes,
# and nothing took the environment back: a ticket whose specification was published still held a
# worktree, and the preview lane addresses the same task id.
#
# What is proved here is the ORDER and the OWNERSHIP. The release is asked for only after the
# publication succeeded and Platform accepted the result, it is asked for as the run that owns
# the environment, and the runner clears nothing itself first — an owned environment's
# unpublished edits are that run's own and are disposable, and an environment it does not own is
# refused by the project with nothing removed.
#
# Driven through the real `claim-once` CLI against the real fake Platform, over a REAL task
# environment built by the project's OWN `bin/worktree` — because every claim here is about what
# is left on disk and which project command was invoked, and a stubbed lifecycle proves neither.
class SpecificationTaskEnvironmentReleaseTest < Minitest::Test
  ISSUE = "EXAMPLE-1"
  TASK = "EXAMPLE-1"
  PACKAGE = "specs/EXAMPLE-1-add-an-export-button"
  PR_URL = "https://github.com/SpecRelay/SpecRelay-Specs/pull/7"

  PACKAGE_CONTENTS = {
    "spec.md" => "# EXAMPLE-1: Add an export button\n\nGenerated by SpecRelay.\n",
    "analysis/business.md" => "# Business analysis\n\nThe reporter retypes rows by hand.\n",
    "analysis/technical.md" => "# Technical analysis\n\nExportReport is the seam.\n",
    "generation-manifest.json" => "{\n  \"generated_by\": \"specrelay\"\n}\n"
  }.freeze

  def setup
    @built = SpecificationWorkspace.build_task_environment
    @root = @built.root
    @io = StringIO.new
    create_task_environment
    write_package(task_package_root)
    build_isolated_workspace
  end

  def teardown
    @platform&.stop
    FileUtils.remove_entry(@built.temp) if @built && File.directory?(@built.temp)
    FileUtils.remove_entry(@gh_dir) if @gh_dir && File.directory?(@gh_dir)
  end

  # ---------------------------------------------------------------- accepted cleanup

  # The outcome. Platform accepted the publication, so the environment this run owns is handed
  # back through the project's own release command, named for that run.
  def test_an_accepted_publication_releases_the_environment_as_its_owning_run
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    assert_equal "published", @platform.last_specification_publication["outcome"], @io.string

    assert_includes worktree_invocations, "release #{TASK} --run-id #{SPEC_RUN} --json"
    refute File.exist?(task_workspace), "the released environment must be gone"
    assert_includes @io.string, "Released this ticket's task environment."
  end

  # The runner removes NOTHING itself. It used to clear the recorded package folder before
  # asking, which meant a refused release left the environment stripped of the accepted files
  # while still allocated. The project is the only thing that removes anything now, so a refusal
  # leaves the environment exactly as the run left it.
  def test_a_refused_release_leaves_the_package_and_the_environment_untouched
    start_platform(release_mode: "refuse")

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    assert_equal PACKAGE_CONTENTS["spec.md"], File.read(File.join(task_package_root, "spec.md"))
    assert_path_exists File.join(task_workspace, "README.md")
    assert_path_exists File.join(task_workspace, "component-a", "app", "services", "export_report.rb")
    assert_includes @io.string, "was NOT released"
  end

  # No claim about which files were cleared or retained. Only the project knows what is left.
  def test_an_incomplete_release_claims_nothing_about_the_files
    start_platform(release_mode: "refuse")
    run_cli

    refute_includes @io.string, "was cleared from this ticket's task environment"
    refute_includes @io.string, "was left in this ticket's task environment"
  end

  # ---------------------------------------------------------------- owned unpublished edits

  # Uncommitted work inside an environment this run owns — including a file a person wrote by
  # hand — is that run's own once the publication has been accepted. It needs no second
  # confirmation and cannot hold the environment open.
  def test_owned_unpublished_edits_do_not_prevent_the_release
    dirty_a_component_repository
    File.write(File.join(task_workspace, "notes-of-my-own.md"), "my working notes\n")
    File.write(File.join(task_package_root, "spec.md"), "# edited by hand after generation\n")
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    assert_equal "published", @platform.last_specification_publication["outcome"], @io.string

    assert_includes worktree_invocations, "release #{TASK} --run-id #{SPEC_RUN} --json"
    refute File.exist?(task_workspace)
  end

  # A tracked accepted package — the shape a round continuing a published specification
  # inherits. Nothing has to be restored or deleted first, because the runner no longer touches
  # the folder at all.
  def test_a_tracked_accepted_package_needs_no_preparation_before_the_release
    commit_the_package_on_the_task_branch
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    assert_includes worktree_invocations, "release #{TASK} --run-id #{SPEC_RUN} --json"
    refute File.exist?(task_workspace)
  end

  # ---------------------------------------------------------------- foreign ownership

  # Ownership replaced between generation and cleanup. The project refuses, and the task package
  # — the thing the runner used to clear FIRST — is untouched.
  def test_an_environment_owned_by_another_run_is_refused_with_the_package_untouched
    ProjectCommand.own!(@root, TASK, "run_somebody_else")
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    assert_equal PACKAGE_CONTENTS["spec.md"], File.read(File.join(task_package_root, "spec.md"))
    assert_path_exists task_workspace
    assert_includes @io.string, "was NOT released"
  end

  # A missing task directory is not a Runner-side "nothing to do". The project still decides,
  # because metadata, a registration or an isolated runtime resource may remain.
  def test_a_missing_task_directory_still_delegates_to_the_projects_release_proof
    FileUtils.rm_rf(task_workspace)
    start_platform

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    assert_includes worktree_invocations, "release #{TASK} --run-id #{SPEC_RUN} --json"
  end

  # ---------------------------------------------------------------- non-accepted retention

  # Platform REFUSED the result. It holds no record, so the package is the replay evidence a
  # retry publishes from and the environment stays where the operator left it.
  def test_a_refused_publication_retains_the_package_and_the_environment
    start_platform
    @platform.publication_response = [ 422, { error: "not acceptable right now" } ]

    assert_equal SpecrelayRunner::CLI::RUN_FAILED, run_cli, @io.string

    assert_path_exists File.join(task_package_root, "spec.md")
    assert_empty worktree_invocations.grep(/\Arelease /), "no release may be asked for"
    assert_path_exists task_workspace
  end

  # The response was LOST. Platform holds no record either way, so the run is offered again and
  # the package has to survive for the replay to converge on the same commit.
  def test_an_unreachable_platform_retains_the_package_and_the_environment
    start_platform
    @platform.publication_response = [ 500, { error: "internal server error" } ]

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string

    assert_path_exists File.join(task_package_root, "spec.md")
    assert_empty worktree_invocations.grep(/\Arelease /), "no release may be asked for"
  end

  # A failure BEFORE the publication reaches GitHub. Nothing was accepted, so nothing is cleaned.
  def test_a_failed_publication_retains_the_package_and_the_environment
    start_platform(gh_mode: "unauthenticated")

    assert_equal SpecrelayRunner::CLI::RUN_FAILED, run_cli, @io.string

    assert_path_exists File.join(task_package_root, "spec.md")
    assert_empty worktree_invocations.grep(/\Arelease /), "no release may be asked for"
  end

  private

  def task_workspace = @built.task_workspace(TASK)
  def task_package_root = File.join(task_workspace, PACKAGE)

  def worktree_invocations
    File.exist?(@built.worktree_log) ? File.read(@built.worktree_log).split("\n") : []
  end

  # The environment the project's own command builds, exactly as generation would have left it:
  # allocated for THIS run, because that is what makes it this run's to hand back.
  def create_task_environment
    out, status = Open3.capture2e(File.join(@root, "bin", "worktree"), "create", TASK,
                                  "--run-id", SPEC_RUN, chdir: @root)
    raise "bin/worktree create failed: #{out}" unless status.success?
  end

  # An operator's own edit to a tracked file of a CONTAINED repository — the shape a per-repository
  # inspection catches and the workspace repository's own `git status` cannot see.
  def dirty_a_component_repository
    path = File.join(task_workspace, "component-a", "app", "services", "export_report.rb")
    File.write(path, "#{File.read(path)}# my own half-finished change\n")
  end

  def write_package(root) = @package_files = write_package_contents(root, PACKAGE_CONTENTS)

  def write_package_contents(root, contents)
    contents.map do |name, body|
      path = File.join(root, name)
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, body)
      { "path" => name, "sha256" => Digest::SHA256.hexdigest(body), "bytes" => body.bytesize }
    end
  end

  # The package as COMMITTED history on the ticket's own branch, which is what a round continuing
  # a published specification inherits.
  def commit_the_package_on_the_task_branch
    git(task_workspace, "add", "--", PACKAGE)
    git(task_workspace, "-c", "user.email=runner@example.test", "-c", "user.name=Runner Test",
        "commit", "-qm", "#{ISSUE}: generated specification package")
  end

  WrittenFile = SpecrelayRunner::Specification::PackageWriter::WrittenFile

  def store
    @store ||= SpecrelayRunner::Specification::PackageWorkspaceStore.new(
      root: SpecificationWorkspace.package_workspace_root(@built.temp), env: { "PATH" => ENV["PATH"] }
    )
  end

  # The retained publication snapshot, holding the SAME bytes as the task environment, built
  # through the production store so publication resumes the shape generation produces.
  def build_isolated_workspace
    store.prepare!
    commands = SpecrelayRunner::Specification::GitCommands.new(checkout_root: @root,
                                                               env: { "PATH" => ENV["PATH"] })
    @workspace = store.create(
      commands: commands, clock: Time, base_commit: git(@root, "rev-parse", "HEAD").strip,
      identity: {
        "run_id" => "run_spec123", "runner_execution_id" => "rex_spec123",
        "runner_id" => "test-runner", "runner_public_id" => "",
        "repository_slug" => "SpecRelay/SpecRelay-Specs",
        "repository_url" => "https://github.com/SpecRelay/SpecRelay-Specs",
        "package_path" => PACKAGE
      }
    )
    write_package(File.join(@workspace.worktree_root, PACKAGE))
    @workspace.finalize!(files: @package_files.map do |file|
      WrittenFile.new(path: file["path"], sha256: file["sha256"], bytes: file["bytes"])
    end)
  end

  def start_platform(gh_mode: "ok", release_mode: nil)
    refuse_release! if release_mode == "refuse"
    @gh_dir, @gh_log, = FakeGithub.gh_bin(mode: gh_mode, pull_request_url: PR_URL,
                                          bare: @built.bares["."])
    @platform = FakePlatform.new(claim_payload: publication_payload).start
    @config = build_config
  end

  # A project whose `release` fails outright, so "the environment was not returned" is an
  # observable state rather than an argument about ordering.
  def refuse_release!
    path = File.join(@root, "bin", "worktree")
    real = "#{path}-real"
    FileUtils.mv(path, real)
    File.write(path, <<~SH)
      #!/usr/bin/env sh
      set -u
      if [ "${1:-}" = "release" ]; then
        echo "release is not available" >&2
        exit 9
      fi
      exec "$(dirname "$0")/worktree-real" "$@"
    SH
    FileUtils.chmod(0o755, path)
  end

  def publication_payload
    spec_publication_payload_for(issue_key: ISSUE, files: @package_files, package_path: PACKAGE,
                                 branch: TASK, workspace_id: @workspace.id)
  end

  def build_config
    path = File.join(Dir.mktmpdir("cfg", @built.temp), "runner.yml")
    File.write(path, <<~YAML)
      platform:
        base_url: #{@platform.base_url}
        token_env: TEST_TOKEN
      runner:
        id: test-runner
        display_name: Test Runner
        claim_policy:
          mode: all_eligible
        specification:
          provider:
            kind: fake
          repository_roots:
            "SpecRelay/SpecRelay-Specs": #{@root}
          context_plus:
            available: true
      workspace_roots:
        tiny-demo-workspace: #{@root}
    YAML
    SpecrelayRunner::Config.load(path)
  end

  def run_cli
    env = { "TEST_TOKEN" => FakePlatform::EXPECTED_TOKEN,
            "PATH" => "#{@gh_dir}:#{ENV['PATH']}", "HOME" => @built.temp }
    SpecrelayRunner::CLI.run(%W[claim-once --config #{@config.source_path}], out: @io, err: @io, env: env)
  end

  def git(root, *args)
    out, status = Open3.capture2e("git", "-C", root, *args)
    raise "git #{args.join(' ')} failed: #{out}" unless status.success?

    out
  end
end
