# frozen_string_literal: true

require_relative "test_helper"
require "digest"
require "open3"

# Continuing a ticket whose specification was already PUBLISHED and ACCEPTED, in a task
# environment built after that round ended.
#
# The chain is the point, and no other suite walks it: an accepted publication commits the
# package with plumbing and pushes it, so it leaves the package on `origin/<branch>` and no local
# branch at all, and the environment is then released. Every other revision test starts from a
# hand-built snapshot and therefore never sees what the NEXT round inherits — an environment
# branched from the base, in which the published specification is not present.
#
# Driven through the real `claim-once` CLI twice, over a REAL task environment built by the
# project's own command, a REAL bare remote and a scriptable fake `gh`: each claim here is about
# what is on disk and in git after the previous phase, and a stubbed lifecycle proves neither.
class SpecificationPublishedContinuationTest < Minitest::Test
  ISSUE = "EXAMPLE-1"
  TASK = "EXAMPLE-1"
  PACKAGE = "specs/EXAMPLE-1-add-an-export-button"
  SPECS_SLUG = "SpecRelay/SpecRelay-Specs"
  PR_URL = "https://github.com/SpecRelay/SpecRelay-Specs/pull/7"

  # Somebody else's open work, on the same remote. The continuation imports the ticket's own
  # branch, so this branch's content must not arrive with it.
  UNRELATED_BRANCH = "somebody-elses-open-work"
  UNRELATED_FILE = "somebody-elses-file.md"

  PACKAGE_CONTENTS = {
    "spec.md" => "# EXAMPLE-1: Add an export button\n\nGenerated by SpecRelay, round 1.\n",
    "analysis/business.md" => "# Business analysis\n\nThe reporter retypes rows by hand.\n",
    "analysis/technical.md" => "# Technical analysis\n\nExportReport is the seam.\n",
    "analysis/input-evidence.md" => "# Input evidence\n\nNo supporting input beyond the ticket.\n"
  }.freeze

  def setup
    @built = SpecificationWorkspace.build_task_environment
    @root = @built.root
    @probe = File.join(@built.temp, "provider-probe.json")
    @io = StringIO.new
    install_two_round_project_command
  end

  def teardown
    @platform&.stop
    FileUtils.remove_entry(@built.temp) if @built && File.directory?(@built.temp)
  end

  # THE chain. The accepted round leaves only `origin/EXAMPLE-1`; the round after it starts from
  # that published head, so the package it revises is tracked history in the ticket's own branch
  # rather than a copy of the same bytes lying untracked beside it.
  #
  # Every fact is read from the environment as the PROVIDER saw it — that is the moment the
  # revision context has to be real, and it is before this round writes a package of its own.
  def test_a_round_after_an_accepted_publication_continues_from_the_published_branch
    published = publish_the_accepted_package
    plant_unrelated_branch

    refute local_branch?(TASK), "the accepted round must leave only the remote branch"
    assert_equal published, remote_head(TASK)

    assert_equal SpecrelayRunner::CLI::SUCCESS, continue_from_the_pull_request, @io.string

    assert_equal TASK, probe["branch"]
    assert_equal published, probe["head"], "the environment must start from the published head"
    assert_equal PACKAGE_CONTENTS.keys.sort, probe["tracked_package_files"].sort
    assert_empty untracked_package_paths, "the published package must not be reproduced untracked"

    # Only this ticket's branch was imported.
    refute probe["unrelated_file_present"], "unrelated branch content must stay out"
    assert_includes remote_branches, UNRELATED_BRANCH
  end

  private

  # ---------------------------------------------------------------- phase 1: accepted round

  # An accepted publication, run the way the product runs it: the package is in the ticket's task
  # environment and in the retained publication snapshot, the runner commits and pushes it, and
  # the accepted result then removes the package and releases the environment. Returns the
  # published head.
  def publish_the_accepted_package
    create_task_environment
    write_package(task_package_root)
    build_isolated_workspace

    @gh_dir, _log, @gh_state = FakeGithub.gh_bin(mode: "ok", pull_request_url: PR_URL,
                                                 bare: @built.bares["."])
    start_platform(spec_publication_payload_for(issue_key: ISSUE, files: @package_files,
                                                package_path: PACKAGE, branch: TASK,
                                                workspace_id: @workspace.id))

    assert_equal SpecrelayRunner::CLI::SUCCESS, run_cli, @io.string
    publication = @platform.last_specification_publication
    assert_equal "published", publication["outcome"], @io.string
    refute_path_exists task_workspace, "the accepted round must release the environment"

    publication["head_commit"]
  end

  # ---------------------------------------------------------------- phase 2: the next round

  # The same ticket, the same pull request, a task environment that does not exist yet.
  def continue_from_the_pull_request
    @platform.stop
    @io = StringIO.new
    @provider = write_probe_provider
    # A fresh invocation log and the SAME pull-request state: this round must find the pull
    # request the accepted round really created.
    @gh_dir, = FakeGithub.gh_bin(mode: "ok", pull_request_url: PR_URL, bare: @built.bares["."],
                                 state: @gh_state)
    start_platform(spec_creation_payload_for(issue_key: ISSUE, existing_pull_request_url: PR_URL))
    run_cli
  end

  # The provider under test: a real process that records the ENVIRONMENT it was handed, in git's
  # own terms, before it answers. "The package is tracked at the published head" is a fact about
  # the tree a provider revises, so it is read from that tree at that moment rather than from the
  # runner's log or from the state this round goes on to write.
  def write_probe_provider
    dir = Dir.mktmpdir("claude-stub", @built.temp)
    package = PACKAGE
    SpecificationWorkspace.write_executable(File.join(dir, "claude"), <<~RUBY)
      #!/usr/bin/env ruby
      require "json"
      if ARGV.first == "--version"
        puts "1.0.0"
        exit 0
      end
      exit 0 if %w[auth login].include?(ARGV.first)

      def git(*args) = IO.popen([ "git", *args ], err: :close, &:read).to_s

      File.write(#{@probe.inspect}, JSON.generate(
        "head" => git("rev-parse", "HEAD").strip,
        "branch" => git("symbolic-ref", "--quiet", "--short", "HEAD").strip,
        "tracked_package_files" => git("ls-files", "--", #{package.inspect})
                                     .split("\\n").map { |path| path.delete_prefix(#{"#{package}/".inspect}) },
        "status" => git("status", "--porcelain", "--untracked-files=all").split("\\n"),
        "unrelated_file_present" => File.exist?(#{UNRELATED_FILE.inspect})
      ))

      puts JSON.generate("type" => "system", "subtype" => "init")
      puts JSON.generate("type" => "result", "subtype" => "success", "is_error" => false,
                         "result" => JSON.generate(#{SpecificationWorkspace.valid_documents(ISSUE).to_json}))
    RUBY
    dir
  end

  # ---------------------------------------------------------------- observation

  def probe = @probe_read ||= JSON.parse(File.read(@probe))

  def untracked_package_paths
    probe["status"].select { |line| line.start_with?("??") && line.include?(PACKAGE) }
  end

  def task_workspace = @built.task_workspace(TASK)
  def task_package_root = File.join(task_workspace, PACKAGE)

  def local_branch?(branch)
    _out, status = SpecificationWorkspace.git(@root, "rev-parse", "--verify", "--quiet",
                                              "refs/heads/#{branch}")
    status.success?
  end

  def remote_head(branch)
    SpecificationWorkspace.git!(@built.bares["."], "rev-parse", "refs/heads/#{branch}").strip
  end

  def remote_branches
    SpecificationWorkspace.git!(@built.bares["."], "for-each-ref", "--format=%(refname:short)",
                                "refs/heads").split("\n")
  end

  # ---------------------------------------------------------------- harness

  # A project command that can build the SAME ticket's environment twice.
  #
  # The shared fixture command always creates with `-b` and releases only the workspace worktree,
  # so a second `create` fails on the branch and the components the first one left behind. The
  # real engine reuses an existing canonical branch and releases every worktree it made, which is
  # the only reason a ticket can be worked on again after a round — and this chain is about what
  # the second round inherits, so the command has to behave like the engine it stands in for.
  def install_two_round_project_command
    components = SpecificationWorkspace::TASK_COMPONENTS.join(" ")
    SpecificationWorkspace.write_executable(File.join(@root, "bin", "worktree"), <<~SH)
      #!/usr/bin/env sh
      set -eu
      ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
      mkdir -p "$ROOT_DIR/.runs"
      echo "$*" >> "$ROOT_DIR/.runs/worktree.log"
      WT="$ROOT_DIR/.runs/worktrees/${2:-}"
      attach() {
        if git -C "$1" show-ref --verify --quiet "refs/heads/$3"; then
          git -C "$1" worktree add -q "$2" "$3"
        else
          git -C "$1" worktree add -q -b "$3" "$2" HEAD
        fi
      }
      case "${1:-}" in
        create)
          mkdir -p "$ROOT_DIR/.runs/worktrees"
          attach "$ROOT_DIR" "$WT" "$2"
          for repo in #{components}; do attach "$ROOT_DIR/$repo" "$WT/$repo" "$2"; done
          ;;
        release)
          for repo in #{components}; do
            git -C "$ROOT_DIR/$repo" worktree remove --force "$WT/$repo" || true
            git -C "$ROOT_DIR/$repo" branch -d "$2" || true
          done
          git -C "$ROOT_DIR" worktree remove --force "$WT"
          git -C "$ROOT_DIR" branch -d "$2" || true
          ;;
        *) echo "usage: worktree create|release <task>" >&2; exit 1 ;;
      esac
    SH
  end

  def create_task_environment
    out, status = Open3.capture2e(File.join(@root, "bin", "worktree"), "create", TASK, chdir: @root)
    raise "bin/worktree create failed: #{out}" unless status.success?
  end

  # An open branch of somebody else's, pushed to the SAME remote. Made in its own clone so the
  # ticket's repositories are left exactly as the accepted round left them.
  def plant_unrelated_branch
    clone = File.join(@built.temp, "somebody-elses-clone")
    out, status = Open3.capture2e("git", "clone", "--quiet", @built.bares["."], clone)
    raise "git clone failed: #{out}" unless status.success?

    SpecificationWorkspace.git!(clone, "checkout", "-q", "-b", UNRELATED_BRANCH)
    File.write(File.join(clone, UNRELATED_FILE), "half-finished work of my own\n")
    SpecificationWorkspace.git!(clone, "add", "-A")
    SpecificationWorkspace.git!(clone, "-c", "user.email=someone@specrelay.local",
                                "-c", "user.name=Someone Else", "commit", "-q", "-m", "my own work")
    SpecificationWorkspace.git!(clone, "push", "-q", "origin", UNRELATED_BRANCH)
  end

  def write_package(root)
    @package_files = PACKAGE_CONTENTS.map do |name, body|
      path = File.join(root, name)
      FileUtils.mkdir_p(File.dirname(path))
      File.write(path, body)
      { "path" => name, "sha256" => Digest::SHA256.hexdigest(body), "bytes" => body.bytesize }
    end
  end

  WrittenFile = SpecrelayRunner::Specification::PackageWriter::WrittenFile

  # The retained publication snapshot, holding the SAME bytes as the task environment, built
  # through the production store so publication resumes the shape generation produces.
  def build_isolated_workspace
    store = SpecrelayRunner::Specification::PackageWorkspaceStore.new(
      root: SpecificationWorkspace.package_workspace_root(@built.temp), env: { "PATH" => ENV["PATH"] }
    )
    store.prepare!
    commands = SpecrelayRunner::Specification::GitCommands.new(checkout_root: @root,
                                                               env: { "PATH" => ENV["PATH"] })
    @workspace = store.create(
      commands: commands, clock: Time,
      base_commit: SpecificationWorkspace.git!(@root, "rev-parse", "HEAD").strip,
      identity: { "run_id" => "run_spec123", "runner_execution_id" => "rex_spec123",
                  "runner_id" => "test-runner", "runner_public_id" => "",
                  "repository_slug" => SPECS_SLUG,
                  "repository_url" => "https://github.com/SpecRelay/SpecRelay-Specs",
                  "package_path" => PACKAGE }
    )
    write_package(File.join(@workspace.worktree_root, PACKAGE))
    @workspace.finalize!(files: @package_files.map do |file|
      WrittenFile.new(path: file["path"], sha256: file["sha256"], bytes: file["bytes"])
    end)
  end

  def start_platform(payload)
    @platform = FakePlatform.new(claim_payload: payload).start
    @config = build_config
  end

  def build_config
    path = File.join(Dir.mktmpdir("cfg", @built.temp), "runner.yml")
    File.write(path, <<~YAML)
      platform:
        base_url: #{@platform.base_url}
        token_env: TEST_TOKEN
      runner:
        id: test-runner
        display_name: Test Runner
        claim_policy:
          mode: all_eligible
        specification:
          repository_roots:
            "#{SPECS_SLUG}": #{@root}
          context_plus:
            available: true
      workspace_roots:
        tiny-demo-workspace: #{@root}
    YAML
    SpecrelayRunner::Config.load(path)
  end

  def run_cli
    path = [ @provider, @gh_dir, ENV["PATH"] ].compact.join(File::PATH_SEPARATOR)
    env = { "TEST_TOKEN" => FakePlatform::EXPECTED_TOKEN, "PATH" => path }
          .merge(SpecificationWorkspace.lane_env(@built.temp))
    SpecrelayRunner::CLI.run(%W[claim-once --config #{@config.source_path}], out: @io, err: @io, env: env)
  end
end
