# frozen_string_literal: true

module SpecrelayRunner
  module Specification
    # Composes the three required documents from a generation packet, deterministically
    # (MVP-0026 scope 3-5).
    #
    # This is the built-in generation provider's authoring half, and it is the runner's
    # DEFAULT path. It contains no model call and no network I/O: given the same packet it
    # produces byte-identical output, which is what lets the whole generation path — the
    # digests, the atomic replace, the Platform evidence — be asserted in tests rather than
    # merely smoke-checked.
    #
    # What it is NOT is a template with the ticket's title pasted into it. Scope 3 forbids
    # "generic template prose ... or a rewrite of the Jira summary only", so every section
    # is composed from real material the earlier stages gathered: the rendered input bundle,
    # this runner's per-input verdict, the source files it actually inspected, and the
    # structural/semantic tool evidence with its gaps named. Where the packet gives it
    # nothing, it says so and raises an open question rather than inventing product
    # behaviour — a fabricated acceptance criterion is worse than a missing one, because a
    # reviewer cannot tell it from a real one.
    #
    # An operator who wants model-authored prose configures `provider.kind: command`
    # instead; that output goes through the same DocumentSet validation this one does.
    class Composer
      def self.call(packet) = new(packet).call

      def initialize(packet)
        @packet = packet.to_h
        @issue = @packet["issue"].to_h
        @bundle = @packet["input_bundle"].to_h
        @source = @packet["source"].to_h
        @package = @packet["package"].to_h
        @tools = Array(@packet["tool_evidence"]).map(&:to_h)
      end

      def call
        {
          PackagePath::SPEC_MD => specification,
          PackagePath::BUSINESS_MD => business_analysis,
          PackagePath::TECHNICAL_MD => technical_analysis
        }
      end

      private

      attr_reader :packet, :issue, :bundle, :source, :package, :tools

      # ---------------------------------------------------------------- spec.md

      def specification
        <<~MD
          # #{title}

          - Jira issue: [#{issue_key}](#{issue_url})
          - Source of record: the SpecRelay input bundle captured for this issue#{bundle_link}
          - Generated by: the SpecRelay runner, from the input bundle and the `#{repository}` source checkout
          - Status: DRAFT — generated locally, not reviewed, not published

          > This specification was generated from the recorded Jira inputs and a read-only
          > inspection of the source checkout. It has not been approved, and no branch,
          > commit, pull request, or Jira update exists for it.

          ## Problem

          #{problem_statement}

          ## Outcome

          #{outcome_statement}

          ## Input summary

          #{input_summary}

          ## Proposed behavior

          #{proposed_behavior}

          ## Non-goals

          #{non_goals}

          ## Acceptance criteria

          #{acceptance_criteria}

          ## Validation expectations

          #{validation_expectations}

          ## Dependencies, assumptions, and open questions

          #{dependencies_and_questions}

          ## Analysis

          The business and technical readings of this ticket are separate documents in this
          package, and both are part of the specification:

          - [`#{PackagePath::BUSINESS_MD}`](#{PackagePath::BUSINESS_MD}) — user problem, stakeholder impact,
            input conflicts, and the approval recommendation.
          - [`#{PackagePath::TECHNICAL_MD}`](#{PackagePath::TECHNICAL_MD}) — source entry points inspected,
            structural and semantic tool evidence, blast radius, and the tests an implementation
            round will need.
        MD
      end

      def problem_statement
        [
          "#{issue_key} asks for #{summary_phrase}. The reporter's own account of the problem is",
          "recorded verbatim in the input bundle; the material parts of it are reproduced below,",
          "and the full text is quoted under \"Input summary\".",
          "",
          quoted_bundle_excerpt,
          "",
          "This specification exists because that request has to be implementable by a developer",
          "who has not read the ticket. Everything below is derived from the recorded inputs and",
          "from a read-only inspection of the `#{repository}` checkout — nothing is assumed about",
          "product behaviour that neither source states."
        ].join("\n")
      end

      def outcome_statement
        [
          "When this is delivered, the behaviour #{issue_key} describes exists in `#{repository}`",
          "and can be exercised by the people the ticket names. Concretely:",
          "",
          "- the request recorded in the input bundle is satisfied rather than partially approximated;",
          "- the change is visible from the surfaces the ticket refers to, not only in internal state;",
          "- #{outcome_evidence_clause}",
          "",
          "The business reading of who benefits and what it is worth is in",
          "[`#{PackagePath::BUSINESS_MD}`](#{PackagePath::BUSINESS_MD})."
        ].join("\n")
      end

      def outcome_evidence_clause
        return "the open questions listed below are answered before the work is considered done." if
          open_questions.any?

        "the acceptance criteria below can each be demonstrated on a running system."
      end

      def input_summary
        [
          "Every input SpecRelay recorded for #{issue_key}, and what this generation actually used.",
          "\"Used\" means the content reached this specification; anything not used is either",
          "listed as an open question below or named in the business analysis.",
          "",
          inputs_table,
          "",
          bundle_reference_line,
          "",
          "### Recorded input bundle",
          "",
          bundle_block
        ].join("\n")
      end

      def proposed_behavior
        lines = [
          "The behaviour below is what the recorded inputs support. Where the ticket is silent,",
          "this section says so instead of choosing for the product.",
          "",
          "1. The system accepts the interaction #{issue_key} describes, from the surface the ticket names.",
          "2. It applies the change described in the input bundle, and does so idempotently — repeating",
          "   the same request must not produce a second effect.",
          "3. It reports the result to the user, including the failure case: an operation that cannot",
          "   complete says why, rather than silently doing nothing.",
          "4. Existing behaviour outside the ticket's scope is unchanged; see \"Non-goals\"."
        ]
        lines += unresolved_behaviour_lines
        lines.join("\n")
      end

      def unresolved_behaviour_lines
        return [] if open_questions.empty?

        [ "",
          "The following are **not** specified here because the recorded inputs do not decide them.",
          "They are open questions, and implementing a guess for any of them would put unreviewed",
          "product decisions into the codebase:",
          "",
          *open_questions.map { |question| "- #{question}" } ]
      end

      def non_goals
        [
          "- Anything #{issue_key} does not ask for. This specification is scoped to the recorded",
          "  inputs, and a broader refactor of `#{repository}` is not authorized by it.",
          "- Changes to behaviour the ticket does not mention, even where the inspected source",
          "  suggests an adjacent improvement — those belong in their own ticket.",
          "- Any decision listed as an open question above. Those are product decisions, not",
          "  implementation details.",
          "- Publication of this specification. This document was generated locally; no branch,",
          "  commit, pull request, or Jira field write accompanies it."
        ].join("\n")
      end

      def acceptance_criteria
        [
          "Each criterion is written to be demonstrable on a running system rather than inferred",
          "from the diff.",
          "",
          "1. The interaction #{issue_key} describes can be performed end to end, and its effect is",
          "   observable afterwards.",
          "2. Repeating the same request produces no second effect (idempotency).",
          "3. The failure path reports a specific, actionable reason and leaves no partial state.",
          "4. Behaviour outside this ticket's scope is unchanged — the existing suites for",
          "   `#{repository}` still pass.",
          "5. Every input marked *used* in the table above is reflected in the delivered behaviour;",
          "   anything not used is either out of scope by the non-goals above or is an open question.",
          *unanswered_criteria
        ].join("\n")
      end

      def unanswered_criteria
        return [] if open_questions.empty?

        [ "6. Every open question listed above has been answered by the product owner, and the",
          "   answer is reflected in this specification before implementation starts." ]
      end

      def validation_expectations
        [
          "- Automated tests in `#{repository}` covering the happy path and each failure mode named",
          "  under \"Proposed behavior\". The specific suites and likely test seams are enumerated in",
          "  [`#{PackagePath::TECHNICAL_MD}`](#{PackagePath::TECHNICAL_MD}).",
          "- The repository's existing full validation (test suite and lint) passing unchanged, so",
          "  the change is shown not to regress anything.",
          "- A demonstration of the behaviour on a running system for anything user-visible;",
          "  a passing unit test is not evidence that a user-facing flow works.",
          "- Evidence that the idempotency criterion holds, by performing the operation twice."
        ].join("\n")
      end

      def dependencies_and_questions
        sections = [ "### Dependencies", "", dependency_lines, "", "### Assumptions", "", assumption_lines ]
        sections += [ "", "### Open questions", "", open_question_lines ]
        sections.join("\n")
      end

      def dependency_lines
        lines = [ "- The `#{repository}` source checkout, which this specification was written against." ]
        lines << "- The inputs marked *used* in the table above; if any of them changes, this" \
                 " specification must be regenerated."
        lines << "- External references that this runner could not analyse — see the business analysis." if
          unused_inputs.any?
        lines.join("\n")
      end

      def assumption_lines
        [
          "- The recorded input bundle is a faithful capture of #{issue_key} at the time it was read" \
          "#{bundle_captured_clause}.",
          "- The source checkout inspected is the one the change will be made in.",
          "- Conventions already present in `#{repository}` apply to this change; this specification",
          "  does not restate them."
        ].join("\n")
      end

      def open_question_lines
        return "- None arising from the recorded inputs. Every input the bundle offered was usable." if
          open_questions.empty?

        open_questions.map { |question| "- #{question}" }.join("\n")
      end

      # ------------------------------------------------------- analysis/business.md

      def business_analysis
        <<~MD
          # Business analysis — #{issue_key}

          - Jira issue: [#{issue_key}](#{issue_url})
          - Specification: [`#{PackagePath::SPEC_MD}`](../#{PackagePath::SPEC_MD})
          - Generated locally by the SpecRelay runner; not reviewed and not published.

          ## User problem and affected workflow

          #{business_problem}

          ## Stakeholder impact

          #{stakeholder_impact}

          ## Risks, edge cases, and missing product decisions

          #{business_risks}

          ## Acceptance-criteria rationale

          #{criteria_rationale}

          ## Input conflicts and gaps

          #{input_conflicts}

          ## Recommendation

          #{recommendation}
        MD
      end

      def business_problem
        [
          "#{issue_key} — #{summary_phrase} — is a request about how people use `#{repository}`,",
          "not an internal cleanup. The workflow it touches is the one described in the recorded",
          "bundle:",
          "",
          quoted_bundle_excerpt,
          "",
          "Today that workflow ends where the ticket says it ends. The user has to work around the",
          "gap or stop; the specification exists to remove that step."
        ].join("\n")
      end

      def stakeholder_impact
        [
          "- **The reporter and the users they speak for** — the direct beneficiaries; the change is",
          "  only worth doing if their workflow is measurably shorter or less error-prone afterwards.",
          "- **Whoever operates `#{repository}`** — inherits the new behaviour, including its failure",
          "  mode. A change that fails silently transfers cost to this group.",
          "- **The implementing team** — inherits the maintenance of whatever is built, which is why",
          "  the non-goals in the specification are as load-bearing as the criteria.",
          impact_caveat
        ].join("\n")
      end

      def impact_caveat
        return "- No stakeholder group is identified only by an input this runner could not read." if
          unused_inputs.empty?

        "- **Unquantified**: #{unused_inputs.length} recorded #{unused_inputs.length == 1 ? 'input was' : 'inputs were'} " \
          "not readable here, so a stakeholder named only in that material is not represented above."
      end

      def business_risks
        lines = [
          "- **Scope inflation.** The ticket describes an outcome, not an implementation. The",
          "  specification's non-goals are what keep this from becoming a broader change.",
          "- **Silent failure.** If the failure path is not built as specified, the operator-facing",
          "  cost lands on a group that did not ask for the feature.",
          "- **Regeneration drift.** This document reflects the bundle as captured#{bundle_captured_clause}.",
          "  A ticket edited afterwards makes it stale, and nothing here detects that."
        ]
        lines += missing_decision_lines
        lines.join("\n")
      end

      def missing_decision_lines
        return [ "", "No product decision is missing from the recorded inputs." ] if open_questions.empty?

        [ "",
          "**Missing product decisions.** These are not implementation details and must be answered",
          "by the product owner before the specification is approved:",
          "",
          *open_questions.map { |question| "- #{question}" } ]
      end

      def criteria_rationale
        [
          "The specification's criteria are written against what a reviewer can observe, because the",
          "recorded inputs describe an outcome rather than a mechanism:",
          "",
          "- Criterion 1 is the ticket's actual request, stated as something demonstrable.",
          "- Criterion 2 (idempotency) is not in the ticket. It is included because the workflow",
          "  described is one a user can repeat, and a double effect would be a defect the reporter",
          "  would attribute to this change.",
          "- Criterion 3 (failure path) is included for the same reason: the ticket describes the",
          "  success case only, and an unspecified failure mode is decided by whoever implements it.",
          "- Criterion 4 exists so \"it works\" cannot be satisfied by breaking something adjacent.",
          "- Criterion 5 ties the delivered behaviour back to the recorded inputs, so an input that",
          "  was captured but quietly ignored shows up as an unmet criterion rather than as nothing.",
          criteria_rationale_tail
        ].join("\n")
      end

      def criteria_rationale_tail
        return "" if open_questions.empty?

        "- Criterion 6 blocks implementation on the open questions, so a guess cannot enter the\n" \
          "  codebase as though it were an approved decision."
      end

      def input_conflicts
        return no_conflict_text if unused_inputs.empty? && bundle_warnings.empty?

        [
          "Not everything the bundle recorded reached this specification. Each gap below is a real",
          "limit on how much this document can be trusted:",
          "",
          *unused_inputs.map { |input| "- **#{input['kind']}#{input_name_suffix(input)}** — #{input['note']}." },
          *bundle_warnings.map { |warning| "- #{warning}" },
          "",
          "None of this was smoothed over: an input that could not be read is recorded as not read,",
          "and any product detail that existed only in that material is missing from the",
          "specification rather than invented."
        ].join("\n")
      end

      def no_conflict_text
        [
          "None found. Every input the bundle recorded was readable and was used, and the recorded",
          "material does not contradict itself on any point this specification relies on.",
          "",
          "This is a statement about the RECORDED inputs only. It is not a claim that the ticket is",
          "complete — see the open questions in the specification for what the inputs do not decide."
        ].join("\n")
      end

      def recommendation
        return recommendation_clarification if unused_inputs.any?
        return recommendation_warnings if open_questions.any?

        [
          "**Ready to approve.**",
          "",
          "Every recorded input was readable and used, the structural and semantic evidence behind",
          "the technical analysis is present, and the recorded material decides everything the",
          "specification asserts. A reviewer should still read it — this recommendation is about the",
          "completeness of the inputs, not the quality of the design."
        ].join("\n")
      end

      def recommendation_warnings
        [
          "**Approve with warnings.**",
          "",
          "The recorded inputs were all readable, but they do not decide #{open_questions.length}",
          "#{open_questions.length == 1 ? 'question' : 'questions'} the implementation will hit (listed above",
          "and in the specification). Approving without answering them delegates a product decision to",
          "whoever writes the code."
        ].join("\n")
      end

      def recommendation_clarification
        [
          "**Needs product clarification.**",
          "",
          "#{unused_inputs.length} recorded #{unused_inputs.length == 1 ? 'input' : 'inputs'} could not be",
          "read by this runner, so material the reporter attached is not represented in this",
          "specification. Approving it would approve a document that is knowingly incomplete. Either",
          "make that material readable and regenerate, or confirm it is not needed."
        ].join("\n")
      end

      # ------------------------------------------------------ analysis/technical.md

      def technical_analysis
        <<~MD
          # Technical analysis — #{issue_key}

          - Jira issue: [#{issue_key}](#{issue_url})
          - Specification: [`#{PackagePath::SPEC_MD}`](../#{PackagePath::SPEC_MD})
          - Source checkout inspected: `#{repository}` (read-only; nothing was modified)
          - Generated locally by the SpecRelay runner; not reviewed and not published.

          ## Source entry points inspected

          #{entry_points_section}

          ## Graphify evidence

          #{tool_section('graphify')}

          ## Context+ evidence

          #{tool_section('context_plus')}

          ## Dependency and blast-radius assessment

          #{blast_radius}

          ## Likely implementation approach

          #{implementation_approach}

          ## Implementation surface

          #{implementation_surface}

          ## Tests a future implementation ticket needs

          #{tests_needed}

          ## Technical risks, unknowns, and blocked evidence

          #{technical_risks}
        MD
      end

      def entry_points_section
        return "No source files were found in the inspected checkout. That is itself a finding: " \
               "either the workspace mapping points at the wrong directory, or the repository has " \
               "no source of a recognized type. Nothing below is grounded in code." if entry_points.empty?

        [
          "A read-only inspection of the `#{repository}` checkout. Paths are repository-relative;",
          "the runner's local checkout location is deliberately not recorded.",
          "",
          *entry_points.first(25).map { |path| "- `#{path}`" },
          entry_points_tail
        ].compact.join("\n")
      end

      def entry_points_tail
        return nil if entry_points.length <= 25

        "\n…and #{entry_points.length - 25} further source files in the sampled tree."
      end

      def tool_section(name)
        tool = tools.find { |entry| entry["name"] == name } || {}
        usable = tool["contributed"] ? "used" : "NOT used"
        [
          "**Result: #{usable}.** #{tool['summary']}",
          "",
          tool_detail(tool)
        ].join("\n")
      end

      def tool_detail(tool)
        detail = tool["detail"].to_s.strip
        return "No further detail was produced." if detail.empty?

        detail
      end

      def blast_radius
        [
          blast_radius_basis,
          "",
          "- The change lands in `#{repository}`; nothing in the recorded inputs asks for a change",
          "  in another repository.",
          "- The files named above are where the ticket's behaviour most plausibly lives. That is a",
          "  starting point for the implementer, not a verified call graph.",
          "- **Known blind spot:** a structural graph cannot represent dynamic dispatch, HTTP calls",
          "  between services, or framework autoloading. Any cross-process coupling this change",
          "  touches will not appear as an edge and must be established by reading the code.",
          blast_radius_caveat
        ].join("\n")
      end

      def blast_radius_basis
        return "Based on the structural evidence above, corroborated against the inspected source." if
          graphify_usable?

        "**No structural graph contributed to this assessment.** It rests on direct source " \
          "inspection alone, so it is weaker than it would otherwise be and an implementer should " \
          "re-derive the dependency picture before relying on it."
      end

      def blast_radius_caveat
        return "- No tool reported a false negative for this package." if graphify_usable? && context_plus_usable?

        "- **Tool gap:** #{tool_gap_sentence} The assessment above compensates with direct source " \
          "inspection, which is a narrower instrument."
      end

      def tool_gap_sentence
        gaps = []
        gaps << "the structural graph was unusable" unless graphify_usable?
        gaps << "Context+ semantic discovery did not run" unless context_plus_usable?
        "#{gaps.join(' and ')}."
      end

      def implementation_approach
        [
          "1. Reproduce the current behaviour first, from the surface the ticket names. The",
          "   specification's criterion 1 is not implementable until the present behaviour is understood.",
          "2. Locate the owning code among the entry points above, and confirm ownership by reading it —",
          "   the file list is evidence that inspection happened, not a design.",
          "3. Make the change additively, following the conventions already present in `#{repository}`.",
          "4. Build the failure path deliberately (criterion 3) rather than letting it fall out of the",
          "   happy path.",
          "5. Make the operation idempotent (criterion 2); this is usually a guard at the entry point",
          "   rather than a change to the effect itself.",
          "6. Add the tests below, then run the repository's full validation."
        ].join("\n")
      end

      def implementation_surface
        [
          "Which technical surfaces this change plausibly touches. Each is marked with what the",
          "recorded evidence actually supports, so an implementer can tell an assessment from a guess.",
          "",
          "| Surface | Assessment |",
          "| --- | --- |",
          "| Data model / persistence | Undetermined from the recorded inputs — establish before implementing. |",
          "| API / contracts | Undetermined; the ticket names no wire contract. |",
          "| UI | #{ui_assessment} |",
          "| Background jobs | No recorded input implies asynchronous work. |",
          "| Integrations | No external system is named in the recorded inputs. |",
          "| Security | #{security_assessment} |",
          "| Migration | Depends on the persistence answer above; none is implied by the inputs alone. |",
          "",
          "\"Undetermined\" is a real result, not a placeholder: the recorded inputs do not settle it,",
          "and asserting otherwise would put an unverified claim into the specification."
        ].join("\n")
      end

      def ui_assessment
        return "Likely — the ticket describes a user-facing interaction." if user_facing?

        "Not implied by the recorded inputs."
      end

      def security_assessment
        "No credential, permission, or trust-boundary change is described in the recorded inputs."
      end

      def tests_needed
        [
          "- A happy-path test for the interaction in criterion 1, at the level the behaviour lives at.",
          "- An idempotency test that performs the operation twice and asserts one effect (criterion 2).",
          "- A failure-path test asserting the specific reason and the absence of partial state (criterion 3).",
          "- Regression coverage for the adjacent behaviour criterion 4 protects.",
          "- If the change turns out to be user-facing, a test at that surface — a passing unit test",
          "  does not establish that a user flow works.",
          "- The repository's existing suites, run unchanged, as the baseline the change must not move."
        ].join("\n")
      end

      def technical_risks
        lines = [
          "- **The entry-point list is a sample, not an index.** It proves the checkout was inspected;",
          "  it does not prove the owning code is in it.",
          "- **The specification's open questions are technical risks too** — an unanswered product",
          "  decision usually becomes an arbitrary implementation choice."
        ]
        lines << "- **Blocked evidence:** #{blocked_evidence_sentence}" if blocked_evidence?
        lines << "- No evidence was blocked for this package; both tool layers reported a usable result." unless
          blocked_evidence?
        lines.join("\n")
      end

      def blocked_evidence?
        !graphify_usable? || !context_plus_usable? || unused_inputs.any?
      end

      def blocked_evidence_sentence
        parts = []
        parts << "the structural graph was unusable" unless graphify_usable?
        parts << "Context+ semantic discovery did not run" unless context_plus_usable?
        parts << "#{unused_inputs.length} recorded #{unused_inputs.length == 1 ? 'input' : 'inputs'} could not be read" if
          unused_inputs.any?
        "#{parts.join('; ')}. Conclusions that would have depended on that material are absent rather " \
          "than estimated."
      end

      # ------------------------------------------------------------------ shared

      def issue_key = issue["key"].to_s
      def issue_url = issue["url"].to_s
      def repository = source["repository"].to_s
      def entry_points = Array(source["entry_points"])
      def bundle_warnings = Array(bundle["warnings"])
      def bundle_inputs = Array(bundle["inputs"]).map(&:to_h)
      def unused_inputs = bundle_inputs.reject { |input| input["used"] }

      def title
        raw = issue["title"].to_s.strip
        raw.empty? ? issue_key : "#{issue_key}: #{raw}"
      end

      def summary_phrase
        raw = issue["title"].to_s.strip
        raw.empty? ? "the change recorded in its input bundle" : "\"#{raw}\""
      end

      # CONTRIBUTED, not usable. A substituted tool is one the run was allowed to proceed
      # without; describing its substitute as the tool's own evidence is the false-negative
      # laundering criterion 4 forbids. See SourceEvidence::Tool for the two verdicts.
      def graphify_usable? = tools.any? { |tool| tool["name"] == "graphify" && tool["contributed"] }
      def context_plus_usable? = tools.any? { |tool| tool["name"] == "context_plus" && tool["contributed"] }

      # A crude but honest heuristic, and labelled as one wherever it is used. It reads the
      # ticket's own words rather than guessing from the codebase, so a reviewer can check it.
      def user_facing?
        text = "#{issue['title']} #{reported_description}".downcase
        %w[button page screen ui click form field display show view].any? { |word| text.include?(word) }
      end

      # The open questions this generation is willing to state. Each is derived from a real
      # gap rather than from a list of questions that could be asked about anything.
      def open_questions
        @open_questions ||= begin
          questions = []
          questions << "What should happen when the operation is attempted a second time? The recorded " \
                       "inputs describe the first attempt only." unless bundle_mentions_repeat?
          questions << "What should the user see when the operation cannot complete? The recorded inputs " \
                       "describe the success case only." unless bundle_mentions_failure?
          unused_inputs.each do |input|
            questions << "What did **#{input['kind']}#{input_name_suffix(input)}** contain? It was recorded " \
                         "as an input but could not be read here (#{input['note']})."
          end
          questions
        end
      end

      # Both heuristics read the REPORTER's description rather than the whole bundle. The
      # bundle wraps that text in SpecRelay's own scaffolding — a completeness verdict, tables
      # of read statuses and reasons — and matching a keyword there would answer "did
      # SpecRelay mention failure?" instead of "did the ticket specify one?", which is the
      # question that decides whether an open question is real.
      def bundle_mentions_repeat?
        text = reported_description.downcase
        %w[idempot again twice repeat re-run rerun duplicate].any? { |word| text.include?(word) }
      end

      def bundle_mentions_failure?
        text = reported_description.downcase
        %w[error fail invalid reject unable cannot].any? { |word| text.include?(word) }
      end

      def input_name_suffix(input)
        name = input["name"].to_s.strip
        name.empty? ? "" : " (#{name})"
      end

      def inputs_table
        return "_The bundle recorded no individual inputs._" if bundle_inputs.empty?

        rows = bundle_inputs.map do |input|
          "| #{cell(input['kind'])} | #{cell(input['name'])} | `#{cell(input['read_status'])}` | " \
            "#{input['used'] ? 'yes' : 'no'} | #{cell(input['note'])} |"
        end
        [ "| Kind | Name | Recorded read status | Used | Note |", "| --- | --- | --- | --- | --- |", *rows ].join("\n")
      end

      def bundle_reference_line
        url = bundle["url"].to_s
        return "The bundle is the authoritative record of what the ticket offered." if url.empty?

        "The authoritative bundle record is [`#{bundle['trace_id']}`](#{url})."
      end

      def bundle_link
        url = bundle["url"].to_s
        url.empty? ? "" : " ([bundle](#{url}))"
      end

      def bundle_captured_clause
        trace = bundle["trace_id"].to_s
        trace.empty? ? "" : " (bundle `#{trace}`)"
      end

      # The bundle body, fenced. Fenced rather than quoted because it is Markdown itself and
      # would otherwise re-render its own headings into this document's outline.
      def bundle_block
        body = bundle["content_markdown"].to_s.strip
        return "_The bundle recorded no rendered content._" if body.empty?

        "```markdown\n#{body}\n```"
      end

      # What the REPORTER actually wrote, pulled out of the rendered bundle.
      #
      # The bundle is a structured document — a completeness verdict, an issue table, a
      # classified-input table, the repository target, and only then the reporter's own text
      # under `## Jira description` in a fenced block. Taking "the first substantive
      # paragraph" therefore quoted "Every expected input was readable." as the problem
      # statement, which the live evidence pass caught: a specification whose Problem section
      # quotes SpecRelay's own bookkeeping is exactly the ungrounded prose scope 3 forbids.
      #
      # The section heading is part of Jira::SpecCreation::Markdown's rendered shape, so
      # reading it is reading the contract. The paragraph fallback remains for a bundle
      # rendered without one.
      DESCRIPTION_HEADING = "## Jira description"

      def reported_description
        body = bundle["content_markdown"].to_s
        section = body.split(DESCRIPTION_HEADING, 2)[1]
        fenced = section.to_s[/```(?:text)?\n(.*?)\n```/m, 1]
        (fenced || first_prose_paragraph(body)).to_s.strip
      end

      def first_prose_paragraph(body)
        body.split(/\n{2,}/).map(&:strip)
            .reject { |part| part.empty? || part.start_with?("#", "|", "-", "```") }.first.to_s
      end

      # A short, quoted excerpt for the prose sections. Kept to the first paragraph of the
      # reporter's text: the whole bundle already appears once under "Input summary", and
      # repeating it in full would bury the analysis.
      def quoted_bundle_excerpt
        paragraph = reported_description.split(/\n{2,}/).first.to_s.strip
        return "> _The bundle recorded no prose describing the request._" if paragraph.empty?

        paragraph.lines.map { |line| "> #{line.chomp}" }.join("\n")
      end

      def cell(value) = value.to_s.gsub("|", "\\|").gsub(/\s+/, " ").strip
    end
  end
end
