# frozen_string_literal: true

module SpecrelayRunner
  module Specification
    # Composes the three required documents from a generation packet, deterministically
    # (MVP-0026 scope 3-5).
    #
    # This is the built-in generation provider's authoring half, and it is the runner's
    # DEFAULT path. It contains no model call and no network I/O: given the same packet it
    # produces byte-identical output, which is what lets the whole generation path — the
    # digests, the atomic replace, the Platform evidence — be asserted in tests rather than
    # merely smoke-checked.
    #
    # What it is NOT is a template with the ticket's title pasted into it. Scope 3 forbids
    # "generic template prose ... or a rewrite of the Jira summary only", so every section
    # is composed from real material the earlier stages gathered: the rendered input bundle,
    # this runner's per-input verdict, the source files it actually inspected, and the
    # structural/semantic tool evidence with its gaps named. Where the packet gives it
    # nothing, it says so and raises an open question rather than inventing product
    # behaviour — a fabricated acceptance criterion is worse than a missing one, because a
    # reviewer cannot tell it from a real one.
    #
    # An operator who wants model-authored prose configures `provider.kind: command`
    # instead; that output goes through the same DocumentSet validation this one does.
    class Composer
      def self.call(packet) = new(packet).call

      def initialize(packet)
        @packet = packet.to_h
        @issue = @packet["issue"].to_h
        @bundle = @packet["input_bundle"].to_h
        @source = @packet["source"].to_h
        @package = @packet["package"].to_h
        @tools = Array(@packet["tool_evidence"]).map(&:to_h)
      end

      def call
        {
          PackagePath::SPEC_MD => specification,
          PackagePath::BUSINESS_MD => business_analysis,
          PackagePath::TECHNICAL_MD => technical_analysis
        }
      end

      private

      attr_reader :packet, :issue, :bundle, :source, :package, :tools

      # ---------------------------------------------------------------- spec.md

      def specification
        <<~MD
          # #{title}

          - Jira issue: [#{issue_key}](#{issue_url})
          - Source of record: the SpecRelay input bundle captured for this issue#{bundle_link}
          - Generated by: #{generated_by}
          - Status: DRAFT — generated locally, not reviewed, not published

          > #{generation_caveat}

          ## Problem

          #{problem_statement}

          ## Outcome

          #{outcome_statement}

          ## Input summary

          #{input_summary}

          ## Proposed behavior

          #{proposed_behavior}

          ## Non-goals

          #{non_goals}

          ## Acceptance criteria

          #{acceptance_criteria}

          ## Validation expectations

          #{validation_expectations}

          ## Dependencies, assumptions, and open questions

          #{dependencies_and_questions}

          ## Analysis

          The business and technical readings of this ticket are separate documents in this
          package, and both are part of the specification:

          - [`#{PackagePath::BUSINESS_MD}`](#{PackagePath::BUSINESS_MD}) — user problem, stakeholder impact,
            input conflicts, and the approval recommendation.
          - [`#{PackagePath::TECHNICAL_MD}`](#{PackagePath::TECHNICAL_MD}) — source entry points inspected,
            structural and semantic tool evidence, blast radius, and the tests an implementation
            round will need.
        MD
      end

      def problem_statement
        [
          "#{issue_key} asks for #{summary_phrase}. #{problem_provenance}",
          "",
          quoted_problem,
          "",
          "This specification exists because that request has to be implementable by a developer",
          "who has not read the ticket. Everything below is derived from the recorded inputs#{grounding_clause} —",
          "nothing is assumed about product behaviour that neither source states."
        ].join("\n")
      end

      # Which paragraph is the problem is not obvious, and getting it wrong is visible in the
      # first section a reader meets. `MAPIAI-47`'s first paragraph is a preamble about the
      # ticket being a review fixture; quoting it unconditionally — which is what the old
      # first-paragraph rule did — put housekeeping where the problem belongs. A ticket with a
      # "Problem" heading has already answered the question, so that answer wins.
      def problem_provenance
        return "The reporter's own \"#{ticket.heading_for(TicketSections::PROBLEM)}\" section is quoted below." if
          ticket.problem?

        "The ticket states no problem section; the reporter's own words are quoted below, and the " \
          "full text is under \"Input summary\"."
      end

      def quoted_problem
        source = ticket.problem.to_s.strip
        source = reported_description.split(/\n{2,}/).first.to_s.strip if source.empty?
        return "> _The bundle recorded no prose describing the request._" if source.empty?

        blockquote(source)
      end

      def blockquote(text)
        text.lines.map { |line| line.strip.empty? ? ">" : "> #{line.chomp}" }.join("\n")
      end

      def outcome_statement
        [
          "When this is delivered, the behaviour #{issue_key} describes exists in `#{repository}`",
          "and can be exercised by the people the ticket names. Concretely:",
          "",
          "- the request recorded in the input bundle is satisfied rather than partially approximated;",
          "- the change is visible from the surfaces the ticket refers to, not only in internal state;",
          "- #{outcome_evidence_clause}",
          "",
          "The business reading of who benefits and what it is worth is in",
          "[`#{PackagePath::BUSINESS_MD}`](#{PackagePath::BUSINESS_MD})."
        ].join("\n")
      end

      def outcome_evidence_clause
        return "the open questions listed below are answered before the work is considered done." if
          open_questions.any?

        "the acceptance criteria below can each be demonstrated on a running system."
      end

      def input_summary
        [
          "Every input SpecRelay recorded for #{issue_key}, and what this generation actually used.",
          "\"Used\" means the content reached this specification; anything not used is either",
          "listed as an open question below or named in the business analysis.",
          "",
          inputs_table,
          "",
          bundle_reference_line,
          "",
          "### Recorded input bundle",
          "",
          bundle_block
        ].join("\n")
      end

      # The ticket's own account of the wanted behaviour comes FIRST and verbatim, followed by
      # the derived numbered statements — and only those the ticket actually supports.
      #
      # The derived list used to assert idempotency and a failure path unconditionally, which
      # against a real ticket for a stateless read-only endpoint produced two invented
      # requirements. Worse, the OPEN QUESTIONS about the same two topics were conditional, so
      # one document could assert idempotency as a requirement and, four sections later, ask
      # who was going to decide it. Both now read the same predicate.
      def proposed_behavior
        lines = [ behaviour_preamble ]
        lines += [ "", reproduced_sections ] if reproduced_sections
        lines += [ "", *derived_behaviour_lines ]
        lines += unresolved_behaviour_lines
        lines.join("\n")
      end

      def behaviour_preamble
        return "The ticket's own description of the wanted behaviour is reproduced first, verbatim. " \
               "The numbered statements after it are derived from the recorded inputs; where the " \
               "ticket is silent, they say so instead of choosing for the product." if reproduced_sections

        "The behaviour below is derived from the recorded inputs. Where the ticket is silent, this " \
          "section says so instead of choosing for the product."
      end

      # Every section of the ticket that is not Problem, Acceptance criteria or Non-goals —
      # each of which has a home of its own in this document. "Edge cases that matter" is a
      # real heading on real tickets and is exactly the material an implementer needs; dropping
      # it because this class has no name for it would be the same defect in a smaller form.
      def reproduced_sections
        return @reproduced_sections if defined?(@reproduced_sections)

        blocks = ticket.other_sections.reject(&:empty?).map do |section|
          "**From the ticket — #{section.heading}:**\n\n#{blockquote(section.body)}"
        end
        @reproduced_sections = blocks.empty? ? nil : blocks.join("\n\n")
      end

      def derived_behaviour_lines
        lines = [ "Derived from the recorded inputs:", "" ]
        numbered = [ "The system accepts the interaction #{issue_key} describes, from the surface the " \
                     "ticket names, and applies the change the input bundle records." ]
        numbered << "Repeating the same request produces no second effect — the ticket calls for " \
                    "idempotent behaviour." if ticket_mentions_repeat?
        numbered << "The failure case reports a specific, actionable reason rather than silently " \
                    "doing nothing." if ticket_mentions_failure?
        numbered << "Existing behaviour outside the ticket's scope is unchanged; see \"Non-goals\"."
        lines + numbered.each_with_index.map { |text, index| "#{index + 1}. #{text}" }
      end

      def unresolved_behaviour_lines
        return [] if open_questions.empty?

        [ "",
          "The following are **not** specified here because the recorded inputs do not decide them.",
          "They are open questions, and implementing a guess for any of them would put unreviewed",
          "product decisions into the codebase:",
          "",
          *open_questions.map { |question| "- #{question}" } ]
      end

      # Where the ticket states its exclusions, they ARE this section — verbatim and attributed
      # — with the standing exclusions appended underneath. The old version dropped all of
      # them and substituted four generic bullets.
      def non_goals
        return standing_non_goals unless ticket.non_goals?

        [
          "**From the ticket's own \"#{ticket.heading_for(TicketSections::NON_GOALS)}\" section, verbatim:**",
          "",
          ticket.non_goals,
          "",
          "In addition, and true of every generated specification:",
          "",
          standing_non_goals
        ].join("\n")
      end

      def standing_non_goals
        [
          "- Anything #{issue_key} does not ask for. This specification is scoped to the recorded",
          "  inputs, and a broader refactor of `#{repository}` is not authorized by it.",
          "- Any decision listed as an open question above. Those are product decisions, not",
          "  implementation details.",
          "- Publication of this specification. This document was generated locally; no branch,",
          "  commit, pull request, or Jira field write accompanies it."
        ].join("\n")
      end

      # The section this MVP is judged on, and the one that was most wrong.
      #
      # A ticket that states its acceptance criteria has already done the hardest part of
      # writing a specification. Replacing them with five generic sentences threw that away and
      # asserted requirements the reporter never made — for `MAPIAI-47`, an idempotency
      # criterion and a failure-path criterion for a stateless read-only GET probe. Where the
      # ticket states criteria, they are reproduced and the derived ones are clearly separated;
      # where it does not, the document says so in its own body, so a reader cannot mistake
      # derived criteria for the reporter's.
      def acceptance_criteria
        return derived_acceptance_criteria unless ticket.acceptance_criteria?

        [
          "**From the ticket's own \"#{ticket.heading_for(TicketSections::ACCEPTANCE)}\" section, " \
          "verbatim. These are the reporter's criteria and are authoritative:**",
          "",
          ticket.acceptance_criteria,
          "",
          "Derived additions, which are this generation's and must be confirmed:",
          "",
          standing_criteria.join("\n")
        ].join("\n")
      end

      def derived_acceptance_criteria
        [
          "**The ticket states no acceptance criteria.** The criteria below are DERIVED from the",
          "recorded inputs by this generation and must be confirmed by the product owner before",
          "implementation starts — they are not the reporter's words.",
          "",
          *derived_criteria_list,
          *standing_criteria
        ].join("\n")
      end

      # Only the criteria the ticket's own text supports. `bundle_mentions_repeat?` and
      # `bundle_mentions_failure?` drive both these and the matching open questions, so the
      # document can no longer require a behaviour and simultaneously ask who will decide it.
      def derived_criteria_list
        lines = [ "- The interaction #{issue_key} describes can be performed end to end, and its effect",
                  "  is observable afterwards." ]
        lines << "- Repeating the same request produces no second effect (idempotency), which the " \
                 "ticket asks for." if ticket_mentions_repeat?
        lines << "- The failure path reports a specific, actionable reason and leaves no partial " \
                 "state, which the ticket asks for." if ticket_mentions_failure?
        lines
      end

      # True of any specification this runner generates, whatever the ticket says, and labelled
      # as this generation's rather than the reporter's.
      def standing_criteria
        lines = [ "- Behaviour outside this ticket's scope is unchanged — the existing suites for",
                  "  `#{repository}` still pass.",
                  "- Every input marked *used* in the table above is reflected in the delivered",
                  "  behaviour; anything not used is out of scope or is an open question." ]
        lines << "- Every open question listed below has been answered by the product owner, and the " \
                 "answer is reflected in this specification before implementation starts." if
          open_questions.any?
        lines
      end

      def validation_expectations
        lines = [
          "- Automated tests in `#{repository}` covering the happy path and each behaviour named",
          "  under \"Proposed behavior\". The specific suites and likely test seams are enumerated in",
          "  [`#{PackagePath::TECHNICAL_MD}`](#{PackagePath::TECHNICAL_MD}).",
          "- The repository's existing full validation (test suite and lint) passing unchanged, so",
          "  the change is shown not to regress anything.",
          "- A demonstration of the behaviour on a running system for anything user-visible;",
          "  a passing unit test is not evidence that a user-facing flow works."
        ]
        # Conditional for the same reason the criterion is: a ticket that never mentions repeat
        # behaviour should not be told to prove idempotency.
        lines << "- Evidence that the idempotency criterion holds, by performing the operation twice." if
          ticket_mentions_repeat?
        lines << "- Evidence for each acceptance criterion the ticket itself states, in the ticket's " \
                 "own terms." if ticket.acceptance_criteria?
        lines.join("\n")
      end

      def dependencies_and_questions
        sections = [ "### Dependencies", "", dependency_lines, "", "### Assumptions", "", assumption_lines ]
        sections += [ "", "### Open questions", "", open_question_lines ]
        sections.join("\n")
      end

      def dependency_lines
        lines = [ inspected_source? ?
                    "- The `#{repository}` source checkout, which this specification was written against." :
                    "- The `#{repository}` source checkout, which this specification was **not** able to " \
                    "read. An implementer must establish the technical picture themselves." ]
        lines << "- The inputs marked *used* in the table above; if any of them changes, this" \
                 " specification must be regenerated."
        lines << "- External references that this runner could not analyse — see the business analysis." if
          unused_inputs.any?
        lines.join("\n")
      end

      def assumption_lines
        lines = [
          "- The recorded input bundle is a faithful capture of #{issue_key} at the time it was read" \
          "#{bundle_captured_clause}."
        ]
        lines << "- The source checkout inspected is the one the change will be made in." if inspected_source?
        lines << "- Conventions already present in `#{repository}` apply to this change; this " \
                 "specification does not restate them."
        lines.join("\n")
      end

      def open_question_lines
        return "- None arising from the recorded inputs. Every input the bundle offered was usable." if
          open_questions.empty?

        open_questions.map { |question| "- #{question}" }.join("\n")
      end

      # ------------------------------------------------------- analysis/business.md

      def business_analysis
        <<~MD
          # Business analysis — #{issue_key}

          - Jira issue: [#{issue_key}](#{issue_url})
          - Specification: [`#{PackagePath::SPEC_MD}`](../#{PackagePath::SPEC_MD})
          - Generated locally by the SpecRelay runner; not reviewed and not published.

          ## User problem and affected workflow

          #{business_problem}

          ## Stakeholder impact

          #{stakeholder_impact}

          ## Risks, edge cases, and missing product decisions

          #{business_risks}

          ## Acceptance-criteria rationale

          #{criteria_rationale}

          ## Input conflicts and gaps

          #{input_conflicts}

          ## Recommendation

          #{recommendation}
        MD
      end

      def business_problem
        [
          "#{issue_key} — #{summary_phrase} — is a request about how people use `#{repository}`,",
          "not an internal cleanup. The workflow it touches is the one described in the recorded",
          "bundle:",
          "",
          quoted_bundle_excerpt,
          "",
          "Today that workflow ends where the ticket says it ends. The user has to work around the",
          "gap or stop; the specification exists to remove that step."
        ].join("\n")
      end

      def stakeholder_impact
        [
          "- **The reporter and the users they speak for** — the direct beneficiaries; the change is",
          "  only worth doing if their workflow is measurably shorter or less error-prone afterwards.",
          "- **Whoever operates `#{repository}`** — inherits the new behaviour, including its failure",
          "  mode. A change that fails silently transfers cost to this group.",
          "- **The implementing team** — inherits the maintenance of whatever is built, which is why",
          "  the non-goals in the specification are as load-bearing as the criteria.",
          impact_caveat
        ].join("\n")
      end

      def impact_caveat
        return "- No stakeholder group is identified only by an input this runner could not read." if
          unused_inputs.empty?

        "- **Unquantified**: #{unused_inputs.length} recorded #{unused_inputs.length == 1 ? 'input was' : 'inputs were'} " \
          "not readable here, so a stakeholder named only in that material is not represented above."
      end

      def business_risks
        lines = [
          "- **Scope inflation.** The ticket describes an outcome, not an implementation. The",
          "  specification's non-goals are what keep this from becoming a broader change.",
          "- **Silent failure.** If the failure path is not built as specified, the operator-facing",
          "  cost lands on a group that did not ask for the feature.",
          "- **Regeneration drift.** This document reflects the bundle as captured#{bundle_captured_clause}.",
          "  A ticket edited afterwards makes it stale, and nothing here detects that."
        ]
        lines += missing_decision_lines
        lines.join("\n")
      end

      def missing_decision_lines
        return [ "", "No product decision is missing from the recorded inputs." ] if open_questions.empty?

        [ "",
          "**Missing product decisions.** These are not implementation details and must be answered",
          "by the product owner before the specification is approved:",
          "",
          *open_questions.map { |question| "- #{question}" } ]
      end

      def criteria_rationale
        [
          "The specification's criteria are written against what a reviewer can observe, because the",
          "recorded inputs describe an outcome rather than a mechanism:",
          "",
          "- Criterion 1 is the ticket's actual request, stated as something demonstrable.",
          "- Criterion 2 (idempotency) is not in the ticket. It is included because the workflow",
          "  described is one a user can repeat, and a double effect would be a defect the reporter",
          "  would attribute to this change.",
          "- Criterion 3 (failure path) is included for the same reason: the ticket describes the",
          "  success case only, and an unspecified failure mode is decided by whoever implements it.",
          "- Criterion 4 exists so \"it works\" cannot be satisfied by breaking something adjacent.",
          "- Criterion 5 ties the delivered behaviour back to the recorded inputs, so an input that",
          "  was captured but quietly ignored shows up as an unmet criterion rather than as nothing.",
          criteria_rationale_tail
        ].join("\n")
      end

      def criteria_rationale_tail
        return "" if open_questions.empty?

        "- Criterion 6 blocks implementation on the open questions, so a guess cannot enter the\n" \
          "  codebase as though it were an approved decision."
      end

      def input_conflicts
        return no_conflict_text if unused_inputs.empty? && bundle_warnings.empty?

        [
          "Not everything the bundle recorded reached this specification. Each gap below is a real",
          "limit on how much this document can be trusted:",
          "",
          *unused_inputs.map { |input| "- **#{input['kind']}#{input_name_suffix(input)}** — #{input['note']}." },
          *bundle_warnings.map { |warning| "- #{warning}" },
          "",
          "None of this was smoothed over: an input that could not be read is recorded as not read,",
          "and any product detail that existed only in that material is missing from the",
          "specification rather than invented."
        ].join("\n")
      end

      def no_conflict_text
        [
          "None found. Every input the bundle recorded was readable and was used, and the recorded",
          "material does not contradict itself on any point this specification relies on.",
          "",
          "This is a statement about the RECORDED inputs only. It is not a claim that the ticket is",
          "complete — see the open questions in the specification for what the inputs do not decide."
        ].join("\n")
      end

      def recommendation
        return recommendation_clarification if unused_inputs.any?
        return recommendation_warnings if open_questions.any?

        [
          "**Ready to approve.**",
          "",
          "Every recorded input was readable and used, the structural and semantic evidence behind",
          "the technical analysis is present, and the recorded material decides everything the",
          "specification asserts. A reviewer should still read it — this recommendation is about the",
          "completeness of the inputs, not the quality of the design."
        ].join("\n")
      end

      def recommendation_warnings
        [
          "**Approve with warnings.**",
          "",
          "The recorded inputs were all readable, but they do not decide #{open_questions.length}",
          "#{open_questions.length == 1 ? 'question' : 'questions'} the implementation will hit (listed above",
          "and in the specification). Approving without answering them delegates a product decision to",
          "whoever writes the code."
        ].join("\n")
      end

      def recommendation_clarification
        [
          "**Needs product clarification.**",
          "",
          "#{unused_inputs.length} recorded #{unused_inputs.length == 1 ? 'input' : 'inputs'} could not be",
          "read by this runner, so material the reporter attached is not represented in this",
          "specification. Approving it would approve a document that is knowingly incomplete. Either",
          "make that material readable and regenerate, or confirm it is not needed."
        ].join("\n")
      end

      # ------------------------------------------------------ analysis/technical.md

      def technical_analysis
        <<~MD
          # Technical analysis — #{issue_key}

          - Jira issue: [#{issue_key}](#{issue_url})
          - Specification: [`#{PackagePath::SPEC_MD}`](../#{PackagePath::SPEC_MD})
          - Source checkout inspected: `#{repository}` (read-only; nothing was modified)
          - Generated locally by the SpecRelay runner; not reviewed and not published.

          ## Source entry points inspected

          #{entry_points_section}

          ## Graphify evidence

          #{tool_section('graphify')}

          ## Context+ evidence

          #{tool_section('context_plus')}

          ## Dependency and blast-radius assessment

          #{blast_radius}

          ## Likely implementation approach

          #{implementation_approach}

          ## Implementation surface

          #{implementation_surface}

          ## Tests a future implementation ticket needs

          #{tests_needed}

          ## Technical risks, unknowns, and blocked evidence

          #{technical_risks}
        MD
      end

      def entry_points_section
        return "**No source file could be read in the inspected checkout, and this generation " \
               "proceeded without one.** That is itself a finding: either the workspace mapping " \
               "points at the wrong directory, or every file under it is binary, oversized, or " \
               "excluded. Nothing below is grounded in code — it is inferred from the ticket. The " \
               "run carries a warning saying so." if entry_points.empty?

        [
          "A read-only inspection of the `#{repository}` checkout. Paths are repository-relative;",
          "the runner's local checkout location is deliberately not recorded.",
          "",
          *entry_points.first(25).map { |path| "- `#{path}`" },
          entry_points_tail
        ].compact.join("\n")
      end

      def entry_points_tail
        return nil if entry_points.length <= 25

        "\n…and #{entry_points.length - 25} further source files in the sampled tree."
      end

      # "Contributed" / "did not contribute", never "used". A tool that was declared available
      # and never queried was previously printed as `Result: used`, which is the single
      # sentence a reader would take as evidence that a semantic pass had happened.
      def tool_section(name)
        tool = tool_entry(name)
        verdict = tool["contributed"] ? "contributed evidence" : "did NOT contribute evidence"
        [
          "**Result: #{verdict}.** #{tool['summary']}",
          "",
          tool_detail(tool)
        ].join("\n")
      end

      def tool_detail(tool)
        detail = tool["detail"].to_s.strip
        return "No further detail was produced." if detail.empty?

        detail
      end

      def blast_radius
        [
          blast_radius_basis,
          "",
          "- The change lands in `#{repository}`; nothing in the recorded inputs asks for a change",
          "  in another repository.",
          "- The files named above are where the ticket's behaviour most plausibly lives. That is a",
          "  starting point for the implementer, not a verified call graph.",
          "- **Known blind spot:** a structural graph cannot represent dynamic dispatch, HTTP calls",
          "  between services, or framework autoloading. Any cross-process coupling this change",
          "  touches will not appear as an edge and must be established by reading the code.",
          blast_radius_caveat
        ].join("\n")
      end

      def blast_radius_basis
        return "Based on the structural evidence above, corroborated against the inspected source." if
          graphify_contributed?

        "**No structural graph contributed to this assessment.** It rests on direct source " \
          "inspection alone, so it is weaker than it would otherwise be and an implementer should " \
          "re-derive the dependency picture before relying on it."
      end

      # Every gap is named, and each one distinguishes CONTRIBUTED from USABLE. "Usable" only
      # ever meant the run was allowed to proceed; printing the two as one verdict is what
      # produced "no tool reported a false negative" next to a layer that had never run.
      def blast_radius_caveat
        gaps = tool_gaps
        return "- Every tool layer contributed evidence to this package; no tool reported a false negative." if
          gaps.empty?

        "- **Tool gap:** #{gaps.join(' ')} The assessment above compensates with direct source " \
          "inspection, which is a narrower instrument."
      end

      def tool_gaps
        gaps = []
        gaps << "The structural graph contributed nothing#{graphify_substitute_clause}." unless
          graphify_contributed?
        # No substitute clause for Context+: the runner cannot probe it at all, so the reason
        # is never "the tool failed and a substitute was accepted". The Context+ section above
        # carries the whole story, including any operator attestation.
        gaps << "No Context+ semantic query was performed by this process." unless context_plus_contributed?
        gaps
      end

      # For Graphify, usable-but-not-contributed means exactly one thing: the probe failed and
      # a substitute was recorded. That is why the run continued. It is NOT the tool's
      # evidence, and the sentence has to say both things or it launders one into the other.
      def graphify_substitute_clause
        return "" unless usable?("graphify")

        " (the run continued on a recorded substitute, which is not the tool's own evidence)"
      end

      def implementation_approach
        [
          "1. Reproduce the current behaviour first, from the surface the ticket names. The",
          "   specification's criterion 1 is not implementable until the present behaviour is understood.",
          "2. Locate the owning code among the entry points above, and confirm ownership by reading it —",
          "   the file list is evidence that inspection happened, not a design.",
          "3. Make the change additively, following the conventions already present in `#{repository}`.",
          "4. Build the failure path deliberately (criterion 3) rather than letting it fall out of the",
          "   happy path.",
          "5. Make the operation idempotent (criterion 2); this is usually a guard at the entry point",
          "   rather than a change to the effect itself.",
          "6. Add the tests below, then run the repository's full validation."
        ].join("\n")
      end

      def implementation_surface
        [
          "Which technical surfaces this change plausibly touches. Each is marked with what the",
          "recorded evidence actually supports, so an implementer can tell an assessment from a guess.",
          "",
          "| Surface | Assessment |",
          "| --- | --- |",
          "| Data model / persistence | Undetermined from the recorded inputs — establish before implementing. |",
          "| API / contracts | Undetermined; the ticket names no wire contract. |",
          "| UI | #{ui_assessment} |",
          "| Background jobs | No recorded input implies asynchronous work. |",
          "| Integrations | No external system is named in the recorded inputs. |",
          "| Security | #{security_assessment} |",
          "| Migration | Depends on the persistence answer above; none is implied by the inputs alone. |",
          "",
          "\"Undetermined\" is a real result, not a placeholder: the recorded inputs do not settle it,",
          "and asserting otherwise would put an unverified claim into the specification."
        ].join("\n")
      end

      def ui_assessment
        return "Likely — the ticket describes a user-facing interaction." if user_facing?

        "Not implied by the recorded inputs."
      end

      def security_assessment
        "No credential, permission, or trust-boundary change is described in the recorded inputs."
      end

      def tests_needed
        [
          "- A happy-path test for the interaction in criterion 1, at the level the behaviour lives at.",
          "- An idempotency test that performs the operation twice and asserts one effect (criterion 2).",
          "- A failure-path test asserting the specific reason and the absence of partial state (criterion 3).",
          "- Regression coverage for the adjacent behaviour criterion 4 protects.",
          "- If the change turns out to be user-facing, a test at that surface — a passing unit test",
          "  does not establish that a user flow works.",
          "- The repository's existing suites, run unchanged, as the baseline the change must not move."
        ].join("\n")
      end

      def technical_risks
        lines = [
          inspection_risk,
          "- **The specification's open questions are technical risks too** — an unanswered product",
          "  decision usually becomes an arbitrary implementation choice."
        ]
        lines << "- **Blocked evidence:** #{blocked_evidence_sentence}" if blocked_evidence?
        lines << "- No evidence was blocked for this package: every recorded input was readable and " \
                 "every tool layer contributed." unless blocked_evidence?
        lines.join("\n")
      end

      # The first risk a reader meets, and it changes completely depending on whether any code
      # was read. "The entry-point list is a sample" is reassuring and wrong when the list is
      # empty.
      def inspection_risk
        return "- **The entry-point list is a sample, not an index.** It proves the checkout was\n" \
               "  inspected; it does not prove the owning code is in it." if inspected_source?

        "- **NO SOURCE WAS INSPECTED.** This is the largest risk in this document. Every technical\n" \
          "  statement below is inferred from the ticket rather than read from code, and an\n" \
          "  implementer should treat the whole analysis as a starting hypothesis."
      end

      def blocked_evidence?
        !graphify_contributed? || !context_plus_contributed? || unused_inputs.any? || !inspected_source?
      end

      # Deliberately reports CONTRIBUTION. A capability the runner cannot probe is always a
      # gap in this document's evidence, even when the operator declared it available — that
      # declaration is what the runner is allowed to proceed on, not what it may claim to have
      # gathered.
      def blocked_evidence_sentence
        parts = []
        parts << "the structural graph contributed nothing" unless graphify_contributed?
        parts << "no Context+ semantic query was performed by this process" unless context_plus_contributed?
        parts << "#{unused_inputs.length} recorded #{unused_inputs.length == 1 ? 'input' : 'inputs'} could not be read" if
          unused_inputs.any?
        "#{parts.join('; ')}. Conclusions that would have depended on that material are absent rather " \
          "than estimated."
      end

      # ------------------------------------------------------------------ shared

      def issue_key = issue["key"].to_s
      def issue_url = issue["url"].to_s
      def repository = source["repository"].to_s
      def entry_points = Array(source["entry_points"])

      # CR-002 must-fix 2. The document asserted source grounding in three places
      # unconditionally, while the inspection had returned zero files and the technical
      # analysis said "Nothing below is grounded in code". A specification that claims to have
      # been written against a checkout it never read is worse than one that admits it did not,
      # because only the second lets a reader discount it correctly.
      def inspected_source? = entry_points.any?

      def grounding_clause
        return " and from a read-only inspection of the `#{repository}` checkout" if inspected_source?

        " ALONE — no source file in the `#{repository}` checkout could be read, so nothing below " \
          "is grounded in code"
      end

      def generated_by
        return "the SpecRelay runner, from the input bundle and the `#{repository}` source checkout" if
          inspected_source?

        "the SpecRelay runner, from the input bundle ONLY — no source file in the " \
          "`#{repository}` checkout could be read"
      end

      def generation_caveat
        return "This specification was generated from the recorded Jira inputs and a read-only " \
               "inspection of the source checkout. It has not been approved, and no branch, commit, " \
               "pull request, or Jira update exists for it." if inspected_source?

        "**No source was inspected.** This specification was generated from the recorded Jira inputs " \
          "alone: the configured source checkout yielded no readable file, so every technical " \
          "statement below is an inference from the ticket rather than from code. It has not been " \
          "approved, and no branch, commit, pull request, or Jira update exists for it."
      end
      def bundle_warnings = Array(bundle["warnings"])
      def bundle_inputs = Array(bundle["inputs"]).map(&:to_h)
      def unused_inputs = bundle_inputs.reject { |input| input["used"] }

      def title
        raw = issue["title"].to_s.strip
        raw.empty? ? issue_key : "#{issue_key}: #{raw}"
      end

      def summary_phrase
        raw = issue["title"].to_s.strip
        raw.empty? ? "the change recorded in its input bundle" : "\"#{raw}\""
      end

      # CONTRIBUTED, not usable — and named that way now, because the old names said `usable?`
      # while reading `contributed`, which is how the document ended up asserting "both tool
      # layers reported a usable result" about a layer that had produced nothing.
      #
      # A substituted tool is one the run was allowed to proceed without; describing its
      # substitute as the tool's own evidence is the false-negative laundering criterion 4
      # forbids. See SourceEvidence::Tool for the two verdicts.
      def tool_entry(name) = tools.find { |tool| tool["name"] == name } || {}
      def contributed?(name) = tool_entry(name)["contributed"] ? true : false
      def usable?(name) = tool_entry(name)["usable"] ? true : false
      def graphify_contributed? = contributed?("graphify")
      def context_plus_contributed? = contributed?("context_plus")

      # The reporter's description, parsed into its own sections. Memoized because six sections
      # of this document read it.
      def ticket = @ticket ||= TicketSections.parse(reported_description)

      # A crude but honest heuristic, and labelled as one wherever it is used. It reads the
      # ticket's own words rather than guessing from the codebase, so a reviewer can check it.
      #
      # WORD BOUNDARIES, not `include?`. Substring matching read `page` inside "homepage", `ui`
      # inside "distinguishable" and `view` inside "REVIEW", so a JSON endpoint with no user
      # interface was reported as `UI | Likely` — a wrong assessment produced by three
      # coincidences in one real ticket.
      def user_facing?
        matches_any?("#{issue['title']} #{reported_description}",
                     %w[button page screen ui click form field display show view])
      end

      def matches_any?(text, words)
        haystack = text.to_s.downcase
        words.any? { |word| /\b#{Regexp.escape(word)}\b/.match?(haystack) }
      end

      # The open questions this generation is willing to state. Each is derived from a real
      # gap rather than from a list of questions that could be asked about anything.
      def open_questions
        @open_questions ||= begin
          questions = []
          questions << "What should happen when the operation is attempted a second time? The recorded " \
                       "inputs describe the first attempt only." unless ticket_mentions_repeat?
          questions << "What should the user see when the operation cannot complete? The recorded inputs " \
                       "describe the success case only." unless ticket_mentions_failure?
          unused_inputs.each do |input|
            questions << "What did **#{input['kind']}#{input_name_suffix(input)}** contain? It was recorded " \
                         "as an input but could not be read here (#{input['note']})."
          end
          questions
        end
      end

      # Both heuristics read the REPORTER's description rather than the whole bundle. The
      # bundle wraps that text in SpecRelay's own scaffolding — a completeness verdict, tables
      # of read statuses and reasons — and matching a keyword there would answer "did
      # SpecRelay mention failure?" instead of "did the ticket specify one?", which is the
      # question that decides whether an open question is real.
      # These two now decide THREE things each — whether the derived behaviour statement is
      # emitted, whether the derived acceptance criterion is emitted, and whether the open
      # question is raised — so that the document can never both require a behaviour and ask
      # who is going to decide it. That contradiction shipped.
      #
      # `idempot` stays a prefix rather than a whole word: "idempotent", "idempotency" and
      # "idempotently" are all the same signal, and `\b` on a prefix is exactly right for it.
      def ticket_mentions_repeat?
        matches_any?(reported_description, %w[idempotent idempotency idempotently again twice repeat
                                              re-run rerun duplicate duplicating second])
      end

      def ticket_mentions_failure?
        matches_any?(reported_description, %w[error errors fail fails failure invalid reject rejects
                                              unable cannot unreadable missing absent])
      end

      def input_name_suffix(input)
        name = input["name"].to_s.strip
        name.empty? ? "" : " (#{name})"
      end

      def inputs_table
        return "_The bundle recorded no individual inputs._" if bundle_inputs.empty?

        rows = bundle_inputs.map do |input|
          "| #{cell(input['kind'])} | #{cell(input['name'])} | `#{cell(input['read_status'])}` | " \
            "#{input['used'] ? 'yes' : 'no'} | #{cell(input['note'])} |"
        end
        [ "| Kind | Name | Recorded read status | Used | Note |", "| --- | --- | --- | --- | --- |", *rows ].join("\n")
      end

      # The bundle is identified by its TRACE ID, never by a link.
      #
      # Platform's artifact URL is `http://127.0.0.1:3200/artifacts/…` for every local
      # operator, and this document is destined for a shared specification repository where
      # that address means a different machine to every reader — or nothing at all. The trace
      # id is stable, greppable, and correct everywhere; whoever holds the Platform instance
      # can resolve it. A dead link that looks live is worse than no link.
      def bundle_reference_line
        trace = bundle["trace_id"].to_s
        return "The bundle is the authoritative record of what the ticket offered." if trace.empty?

        "The authoritative bundle record is trace `#{trace}` in the SpecRelay Platform that " \
          "captured it."
      end

      def bundle_link
        trace = bundle["trace_id"].to_s
        trace.empty? ? "" : " (bundle trace `#{trace}`)"
      end

      def bundle_captured_clause
        trace = bundle["trace_id"].to_s
        trace.empty? ? "" : " (bundle `#{trace}`)"
      end

      # The bundle body, fenced. Fenced rather than quoted because it is Markdown itself and
      # would otherwise re-render its own headings into this document's outline.
      #
      # The fence LENGTH is chosen from the body, and that is not a detail. The bundle always
      # carries a fenced block of its own — Platform's renderer puts the reporter's
      # description in one — so a hardcoded three-backtick fence closed on the bundle's fence
      # and left the remaining six sections of this document inside a code block that was
      # never closed. That shipped. See Markdown.fenced, which is now the only sanctioned way
      # to embed text this process did not author.
      def bundle_block
        body = bundle["content_markdown"].to_s.strip
        return "_The bundle recorded no rendered content._" if body.empty?

        Markdown.fenced(body, info: "markdown")
      end

      # What the REPORTER actually wrote, pulled out of the rendered bundle.
      #
      # The bundle is a structured document — a completeness verdict, an issue table, a
      # classified-input table, the repository target, and only then the reporter's own text
      # under `## Jira description` in a fenced block. Taking "the first substantive
      # paragraph" therefore quoted "Every expected input was readable." as the problem
      # statement, which the live evidence pass caught: a specification whose Problem section
      # quotes SpecRelay's own bookkeeping is exactly the ungrounded prose scope 3 forbids.
      #
      # The section heading is part of Jira::SpecCreation::Markdown's rendered shape, so
      # reading it is reading the contract. The paragraph fallback remains for a bundle
      # rendered without one.
      DESCRIPTION_HEADING = "## Jira description"

      # The fence around that section is NOT always three backticks: Platform lengthens it
      # when the reporter's own text contains a backtick run. Matching a fixed ``` here would
      # quietly fall through to the paragraph heuristic for exactly the descriptions most
      # likely to contain code — so the opening run is captured and the closing one matched
      # against it.
      DESCRIPTION_BODY = /^(`{3,})[^\n`]*\n(.*?)\n\1`*[ \t]*$/m

      def reported_description
        body = bundle["content_markdown"].to_s
        section = body.split(DESCRIPTION_HEADING, 2)[1]
        fenced = section.to_s[DESCRIPTION_BODY, 2]
        (fenced || first_prose_paragraph(body)).to_s.strip
      end

      def first_prose_paragraph(body)
        body.split(/\n{2,}/).map(&:strip)
            .reject { |part| part.empty? || part.start_with?("#", "|", "-", "```") }.first.to_s
      end

      # A short, quoted excerpt for the prose sections. Kept to the first paragraph of the
      # reporter's text: the whole bundle already appears once under "Input summary", and
      # repeating it in full would bury the analysis.
      def quoted_bundle_excerpt
        paragraph = reported_description.split(/\n{2,}/).first.to_s.strip
        return "> _The bundle recorded no prose describing the request._" if paragraph.empty?

        paragraph.lines.map { |line| "> #{line.chomp}" }.join("\n")
      end

      def cell(value) = value.to_s.gsub("|", "\\|").gsub(/\s+/, " ").strip
    end
  end
end
